var teams = {
  1: {
    members: "余思龙、闵烁、李骋",
    school: "安徽大学",
    team: "瑞文欧米茄",
    type: "type1",
  },
  2: {
    members: "黄超、王北辰、刘桁铭",
    school: "北方工业大学",
    team: "好坏小姐",
    type: "type1",
  },
  3: {
    members: "林达华、于新程、郭志坚",
    school: "北方工业大学",
    team: "头奖",
    type: "type2 unofficial",
  },
  4: {
    members: "吴嘉帅、张家宁、陈冠华",
    school: "北华大学",
    team: "纯牛奶",
    type: "type1",
  },
  5: {
    members: "姚晗荟、王旭、李军航",
    school: "北华大学",
    team: "和光同尘",
    type: "type2 unofficial",
  },
  6: {
    members: "陈君杰、王振、杨佳乐",
    school: "北华大学",
    team: "求芭比母捏牛~",
    type: "type2 unofficial",
  },
  7: {
    members: "李宁、王颖、涂伟鸿",
    school: "北华大学",
    team: "以上队伍为全部获奖名单，请各队伍依次有序离场，谢谢大家",
    type: "type1",
  },
  8: {
    members: "郭城志、陈宇、徐舟子",
    school: "北京大学",
    team: "巨大的金刚鸽子",
    type: "type1",
  },
  9: {
    members: "刘俊豪、陈官厅、刘雨俊",
    school: "北京大学",
    team: "马猴烧酒",
    type: "type1",
  },
  10: {
    members: "吕秋实、屠学畅、张博为",
    school: "北京大学",
    team: "你这题保熟吗",
    type: "type1",
  },
  11: {
    members: "王展鹏、罗煜翔、蒋凌宇",
    school: "北京大学",
    team: "重生之我是菜狗",
    type: "type1",
  },
  12: {
    members: "谢文杰、杨文登、黄凝霜",
    school: "北京大学",
    team: "七题就是胜利",
    type: "type2 unofficial",
  },
  13: {
    members: "曹原、陈胤戬、吴孟周",
    school: "北京大学",
    team: "你对队伍名有头猪吗",
    type: "type2 unofficial",
  },
  14: {
    members: "赵子涵、程泽轩、张思淼",
    school: "北京航空航天大学",
    team: "我完全不会.jpg",
    type: "type1",
  },
  15: {
    members: "温佳昊、韩一、吕诚鑫",
    school: "北京航空航天大学",
    team: "又是困难的取名时间了",
    type: "type1",
  },
  16: {
    members: "李佩峰、熊伟、曾朴凡",
    school: "北京化工大学",
    team: "红绿灯",
    type: "type2 unofficial",
  },
  17: {
    members: "洪枢适、曾梓勋、梁凯星",
    school: "北京化工大学",
    team: "自己相似的两性具有",
    type: "type1",
  },
  18: {
    members: "邵天语、杨致远、王麒皓",
    school: "北京交通大学",
    team: "届不到的AC",
    type: "type1",
  },
  19: {
    members: "黄泽华、蔡子祺、杨佳昊",
    school: "北京交通大学",
    team: "卷心菜",
    type: "type1",
  },
  20: {
    members: "杨纪升、何昌鹏、许根瑞",
    school: "北京交通大学",
    team: "隆中对键盘分队",
    type: "type1",
  },
  21: {
    members: "于瀚文、孙嘉珺、赖昱行",
    school: "北京理工大学",
    team: "挂件挂挂件",
    type: "type1",
  },
  22: {
    members: "闫方昭、张至鑫、袁奕晨",
    school: "北京理工大学",
    team: "来口汤",
    type: "type1",
  },
  23: {
    members: "周楷、邱明亮、张睿敏",
    school: "北京林业大学",
    team: "好潮如评",
    type: "type2 unofficial",
  },
  24: {
    members: "陈浩翔、黄梓铭、康旭",
    school: "北京林业大学",
    team: "杂毛小鸡",
    type: "type1",
  },
  25: {
    members: "王小普、刘语柔、陆春酉",
    school: "北京师范大学",
    team: "网络流",
    type: "type1",
  },
  26: {
    members: "张睿琪、臧祝利、张弘强",
    school: "北京师范大学",
    team: "无敌舰队",
    type: "type2 unofficial",
  },
  27: {
    members: "彭泊词、汤昕宇、娄格格",
    school: "北京师范大学",
    team: "谢谢凯文",
    type: "type2 unofficial",
  },
  28: {
    members: "徐若翔、何佳文、段欣然",
    school: "北京师范大学",
    team: "野指针",
    type: "type1",
  },
  29: {
    members: "马千里、叶骏贤、王博",
    school: "北京师范大学珠海校区",
    team: "代码都队",
    type: "type1",
  },
  30: {
    members: "刘雨杭、姚梦俊、刘东轩",
    school: "北京师范大学珠海校区",
    team: "公费旅游团？不可能的",
    type: "type1",
  },
  31: {
    members: "鲍高文、马帅雯、朴盛荷",
    school: "北京信息科技大学",
    team: "我觉得很队",
    type: "type2 unofficial",
  },
  32: {
    members: "刘泽昊、宋开元、苏永鑫",
    school: "北京信息科技大学",
    team: "走到湖边就会哈拉一下买一杯美式",
    type: "type1",
  },
  33: {
    members: "汤子唯、董凯文、高畅",
    school: "北京邮电大学",
    team: "NMLPC",
    type: "type2 unofficial",
  },
  34: {
    members: "石映奇、黄思喆、王肇汉",
    school: "北京邮电大学",
    team: "北邮负一队",
    type: "type1",
  },
  35: {
    members: "马玉龙、代皓燃、佘俊达",
    school: "北京邮电大学",
    team: "打代码",
    type: "type1",
  },
  36: {
    members: "陈冠州、赵昕鹏、李亦非",
    school: "北京邮电大学",
    team: "三只喵喵一锅汤",
    type: "type1",
  },
  37: {
    members: "谢骞、崔家瑞、罗毅锐",
    school: "北京邮电大学",
    team: "托马斯今天吃什么",
    type: "type2 unofficial",
  },
  38: {
    members: "任飞、李知拙、简宇卿",
    school: "北京邮电大学",
    team: "野鸡大队",
    type: "type2 unofficial",
  },
  39: {
    members: "杨天智、刘枭、余晨",
    school: "成都东软学院",
    team: "wa哈哈",
    type: "type2 unofficial",
  },
  40: {
    members: "武晓飞、马千里、赵一鑫",
    school: "成都东软学院",
    team: "大连东软你们好！",
    type: "type1",
  },
  41: {
    members: "闫俊毅、范云飞、周海君",
    school: "成都东软学院",
    team: "给我wa",
    type: "type2 unofficial",
  },
  42: {
    members: "王淇龙、朱菲、钱思琪",
    school: "成都东软学院",
    team: "我样例过了",
    type: "type1",
  },
  43: {
    members: "喻若舟、陈柯源、刘浩",
    school: "成都锦城学院",
    team: "三核单线程",
    type: "type2 unofficial",
  },
  44: {
    members: "郭涵涛、刘逸飞、关泽群",
    school: "大连大学",
    team: "活着AC",
    type: "type1",
  },
  45: {
    members: "钱坤、李雁志、葛俊辰",
    school: "大连理工大学",
    team: "dlut01",
    type: "type1",
  },
  46: {
    members: "王玉宁、刘政、宋佳俊",
    school: "大连理工大学",
    team: "阿巴阿巴",
    type: "type1",
  },
  47: {
    members: "江雨桐、夏鸿康、李冠霖",
    school: "大连理工大学",
    team: "三带一",
    type: "type1",
  },
  48: {
    members: "汪语桐、山佩永、张能",
    school: "电子科技大学",
    team: "UESTC_样例输入",
    type: "type2 unofficial",
  },
  49: {
    members: "张子牛、王致远、张梅宏",
    school: "电子科技大学",
    team: "UESTC_这是什么牛马队",
    type: "type2 unofficial",
  },
  50: {
    members: "罗嘉诚、林华伦、吴宇航",
    school: "电子科技大学",
    team: "飞土豆",
    type: "type1",
  },
  51: {
    members: "冯书瀚、刘轩、张鸿浩",
    school: "电子科技大学",
    team: "谁给我报的名？",
    type: "type1",
  },
  52: {
    members: "张镕麒、吴晓玉、梁晖",
    school: "电子科技大学",
    team: "我们仍未知道那天WA的原因",
    type: "type2 unofficial",
  },
  53: {
    members: "王昱栋、张乐恒、罗旅洲",
    school: "电子科技大学",
    team: "星际幽灵",
    type: "type1",
  },
  54: {
    members: "王乐言、陈彦澍、曹城宇",
    school: "东北大学",
    team: "东北大学_米饭还没点",
    type: "type1",
  },
  55: {
    members: "曹立菲、曹怡明、冯鼎容",
    school: "东北大学秦皇岛分校",
    team: "bug都改队",
    type: "type1",
  },
  56: {
    members: "张旭、王敬群、梁迪",
    school: "东北大学秦皇岛分校",
    team: "该队名未通过审核",
    type: "type1",
  },
  57: {
    members: "张烨槟、张逸凡、沈晓汐",
    school: "东北大学秦皇岛分校",
    team: "就这场了",
    type: "type1",
  },
  58: {
    members: "吴宗航、陈李宏、牟东龙",
    school: "东北电力大学",
    team: "AC了但完全没有AC",
    type: "type1",
  },
  59: {
    members: "徐浩东、关凯铭、李翔宇",
    school: "东北电力大学",
    team: "HAL 9000",
    type: "type1",
  },
  60: {
    members: "冯楚婷、李贵祥、徐昕阳",
    school: "东北电力大学",
    team: "tan90°",
    type: "type2 unofficial",
  },
  61: {
    members: "车宇航、汪永超、汪琦霖",
    school: "东北电力大学",
    team: "不会起名",
    type: "type2 unofficial",
  },
  62: {
    members: "李一辰、方震、邱科悦",
    school: "东北林业大学",
    team: "林大施工队",
    type: "type1",
  },
  63: {
    members: "蒋世超、常中一、张哲",
    school: "东北林业大学",
    team: "吾有一术，名曰暴力",
    type: "type1",
  },
  64: {
    members: "潘航、付钧元、周思乐",
    school: "东北林业大学",
    team: "线性封闭",
    type: "type1",
  },
  65: {
    members: "唐瑀佳、李兴锐、路号号",
    school: "东北农业大学",
    team: "不差这二十分钟",
    type: "type1",
  },
  66: {
    members: "霍欣彤、李子豪、刘禹",
    school: "东北农业大学",
    team: "英语挂了就寄",
    type: "type1",
  },
  67: {
    members: "胡潇、范耀天、曾令树",
    school: "东北师范大学",
    team: "极光",
    type: "type2 unofficial",
  },
  68: {
    members: "邹宇明、刘思博、胡哲瑜",
    school: "东北师范大学",
    team: "荧惑守心",
    type: "type2 unofficial",
  },
  69: {
    members: "童浩龙、徐文浩、唐佳成",
    school: "东北师范大学",
    team: "长夜漫漫",
    type: "type1",
  },
  70: {
    members: "李嘉琦、史曼玲、刘一木",
    school: "东北师范大学",
    team: "竹取飞翔",
    type: "type1",
  },
  71: {
    members: "黄天宇、张皓、田昊冬",
    school: "东南大学",
    team: "未命名",
    type: "type1",
  },
  72: {
    members: "谢天意、谢腾飞、储思晴",
    school: "阜阳师范大学",
    team: "我就想拿个牌儿",
    type: "type1",
  },
  73: {
    members: "吴汝钊、陈浩鹏、卓曜龙",
    school: "广东工业大学",
    team: "金缕衣",
    type: "type1",
  },
  74: {
    members: "王泽荣、黄铭晖、杨德荣",
    school: "广东工业大学",
    team: "没吃饱没睡好",
    type: "type2 unofficial",
  },
  75: {
    members: "马一凡、陈逸霖、张茜",
    school: "广东工业大学",
    team: "强力去污粉",
    type: "type1",
  },
  76: {
    members: "王若楠、麦俊宇、叶枫",
    school: "广东工业大学",
    team: "宇宙年级舰队",
    type: "type2 unofficial",
  },
  77: {
    members: "何金洺、孙城涛、洪越",
    school: "广西大学",
    team: "我永远喜欢雪之下雪乃",
    type: "type1",
  },
  78: {
    members: "鲁智昊、周博睿、王鹏程",
    school: "桂林电子科技大学",
    team: "罚时不到两位数就算大成功",
    type: "type1",
  },
  79: {
    members: "刘思语、汪庭浩、黄思晨",
    school: "桂林电子科技大学",
    team: "无名之辈",
    type: "type1",
  },
  80: {
    members: "宁申恺、苏一水、李立",
    school: "桂林电子科技大学",
    team: "广西小清华",
    type: "type1",
  },
  81: {
    members: "朱卓锋、董理、王荣航",
    school: "国防科技大学",
    team: "三个点金手",
    type: "type2 unofficial",
  },
  82: {
    members: "李雯丽、孙晓帆、陈铭",
    school: "国防科技大学",
    team: "湘江后浪",
    type: "type1",
  },
  83: {
    members: "祁展华、王羽婷、朱峰",
    school: "哈尔滨工业大学",
    team: "男道你不酮意这个队名",
    type: "type1",
  },
  84: {
    members: "李杰、宋珂源、崔玉坤",
    school: "哈尔滨工业大学",
    team: "三个演员",
    type: "type1",
  },
  85: {
    members: "王晓亮、徐放、金义扬",
    school: "哈尔滨工业大学",
    team: "三维半布丁交",
    type: "type1",
  },
  86: {
    members: "贾棠惠、李忠浩、刘江涛",
    school: "哈尔滨工业大学（深圳）",
    team: "比奇堡的快乐时光",
    type: "type1",
  },
  87: {
    members: "吴泽楷、唐楷杰、李彬昌",
    school: "哈尔滨工业大学（深圳）",
    team: "冰糖屋",
    type: "type1",
  },
  88: {
    members: "梁珊、任秦江、卢郡然",
    school: "哈尔滨工业大学（深圳）",
    team: "删库跑路",
    type: "type1",
  },
  89: {
    members: "王皓翰、周政、王子建",
    school: "哈尔滨工业大学（威海）",
    team: "Siberia Wolves",
    type: "type1",
  },
  90: {
    members: "解裕懋、曹瑞宁、戚煜",
    school: "哈尔滨工业大学（威海）",
    team: "队友打的都队",
    type: "type1",
  },
  91: {
    members: "刘新一、和树繁、苑世豪",
    school: "哈尔滨工业大学（威海）",
    team: "掘金打铁",
    type: "type1",
  },
  92: {
    members: "苏世睿、赵禹博、张高源",
    school: "哈尔滨工业大学（威海）",
    team: "威士忌泡泡",
    type: "type1",
  },
  93: {
    members: "温亚龙、赵连祥、杨皓祥",
    school: "哈尔滨华德学院",
    team: "听党指挥",
    type: "type1",
  },
  94: {
    members: "郑然、马英杰、王天昊",
    school: "哈尔滨理工大学",
    team: "哈理工04队",
    type: "type1",
  },
  95: {
    members: "胡启炜、吕锦泽、秦爽浪",
    school: "哈尔滨理工大学",
    team: "哈理工05队",
    type: "type1",
  },
  96: {
    members: "张博文、王梓镔、吴兆远",
    school: "哈尔滨商业大学",
    team: "哈商大先行者二队",
    type: "type1",
  },
  97: {
    members: "赵晨星、葛钦凡、周一凡",
    school: "哈尔滨商业大学",
    team: "哈商大先行者四队",
    type: "type1",
  },
  98: {
    members: "何圣娟、翁勇辉、杜维缘",
    school: "哈尔滨商业大学",
    team: "哈商大先行者一队",
    type: "type1",
  },
  99: {
    members: "李滨、张宏悦、周思宇",
    school: "哈尔滨师范大学",
    team: "Coding咚",
    type: "type1",
  },
  100: {
    members: "李东璋、吴志涛、陈珊",
    school: "哈尔滨师范大学",
    team: "SimRobot",
    type: "type1",
  },
  101: {
    members: "付鹤飞、鲁伟毫、韩艺博",
    school: "哈尔滨师范大学",
    team: "可是可是",
    type: "type2 unofficial",
  },
  102: {
    members: "吕俊杰、邹宇琦、乔航",
    school: "哈尔滨师范大学",
    team: "以一当十队",
    type: "type2 unofficial",
  },
  103: {
    members: "刘彬、彭俊、王毅",
    school: "哈尔滨学院",
    team: "哈学院1队",
    type: "type1",
  },
  104: {
    members: "张瑞来、黎亮欢、李星伶",
    school: "哈尔滨学院",
    team: "哈学院2队",
    type: "type1",
  },
  105: {
    members: "刘礼铭、张晓晗、于岩斌",
    school: "哈尔滨学院",
    team: "哈学院3队",
    type: "type2 unofficial",
  },
  106: {
    members: "刘梦宇、龙卓希、吴长和",
    school: "哈尔滨学院",
    team: "哈学院4队",
    type: "type2 unofficial",
  },
  107: {
    members: "汤丰瑜、郑凯心、侯津涛",
    school: "杭州电子科技大学",
    team: "杭电2021-1队",
    type: "type1",
  },
  108: {
    members: "杜志远、刘梓灏、李丰",
    school: "杭州电子科技大学",
    team: "杭电2021-5队",
    type: "type1",
  },
  109: {
    members: "林伟杰、宁骐鸣、阮宇宁",
    school: "杭州电子科技大学",
    team: "杭电2021-6队",
    type: "type1",
  },
  110: {
    members: "李彦庆、杨云龙、林泓佺",
    school: "杭州师范大学",
    team: "为了和平",
    type: "type1",
  },
  111: {
    members: "包嘉城、徐烨超、宋蹴翰",
    school: "杭州师范大学",
    team: "我超勇的",
    type: "type2 unofficial",
  },
  112: {
    members: "姜万磊、何昕悦、胡代金",
    school: "合肥工业大学宣城校区",
    team: "跑快快",
    type: "type1",
  },
  113: {
    members: "冯新皓、孟宪周、李辰",
    school: "河北工业大学",
    team: "此情可待成追忆",
    type: "type1",
  },
  114: {
    members: "马晓丹、葛子赫、杨子棋",
    school: "河北工业大学",
    team: "只是当时已惘然",
    type: "type1",
  },
  115: {
    members: "侯思琪、周佳璐、张天伟",
    school: "河北师范大学",
    team: "大一学弟带两个大二学姐打星的故事",
    type: "type2 unofficial",
  },
  116: {
    members: "赵洪博、胡超然、徐悦然",
    school: "河北师范大学",
    team: "红糖味小麻花",
    type: "type1",
  },
  117: {
    members: "孙一、仇东豪、王严振",
    school: "河北师范大学",
    team: "键上翻花",
    type: "type2 unofficial",
  },
  118: {
    members: "吕占捷、张圣哲、黄巍赟",
    school: "河北师范大学",
    team: "来哈尔滨偷个银",
    type: "type1",
  },
  119: {
    members: "杨顺昌、程子蕴、陈雅文",
    school: "河北师范大学",
    team: "绿茶味口香糖",
    type: "type2 unofficial",
  },
  120: {
    members: "王浩哲、李承州、周雲冲",
    school: "河北师范大学附属民族学院",
    team: "我们真的是炮灰",
    type: "type1",
  },
  121: {
    members: "高康悦、张星宇、肖潇",
    school: "河海大学",
    team: "埃派克斯",
    type: "type1",
  },
  122: {
    members: "李祖卫、秦卓、王梦贤",
    school: "河南财政金融学院",
    team: "wawa自动机",
    type: "type1",
  },
  123: {
    members: "刘邦龙、闫沛霖、蔡俊宇",
    school: "河南大学",
    team: "望星",
    type: "type1",
  },
  124: {
    members: "叶力源、党韩昱、张宇",
    school: "河南大学",
    team: "星月",
    type: "type1",
  },
  125: {
    members: "李士强、师明宇、李凯杰",
    school: "河南农业大学",
    team: "ACM，我只打银川",
    type: "type1",
  },
  126: {
    members: "伍宝骅、李冠洋、徐振寓",
    school: "黑龙江大学",
    team: "hs yyds!~",
    type: "type1",
  },
  127: {
    members: "宋福海、邓基霄、丁浩康",
    school: "黑龙江大学",
    team: "拭暗晨曦",
    type: "type1",
  },
  128: {
    members: "黄玉胜、张功鉴、孙纤",
    school: "黑龙江科技大学",
    team: "USTH_从零开始",
    type: "type1",
  },
  129: {
    members: "李松岭、梁傲雪、邓波",
    school: "黑龙江科技大学",
    team: "USTH_签到万岁",
    type: "type2 unofficial",
  },
  130: {
    members: "涂诺辛格、熊黎、吴徵靖",
    school: "湖北中医药大学",
    team: "人均身高180",
    type: "type1",
  },
  131: {
    members: "陈叹、张龙韬、薛宇超",
    school: "湖南大学",
    team: "极限二带一",
    type: "type1",
  },
  132: {
    members: "阳彦君、陈介东、谭画",
    school: "湖南科技大学",
    team: "楚门的金色世界",
    type: "type1",
  },
  133: {
    members: "王辰宇、涂定凡、黄沛遥",
    school: "湖南师范大学",
    team: "拿个嘤回家",
    type: "type1",
  },
  134: {
    members: "廖世兴、欧阳亨杰、魏微",
    school: "湖南中医药大学",
    team: "触底反弹",
    type: "type1",
  },
  135: {
    members: "黄宇廷、常远帆、罗子涵",
    school: "华东交通大学",
    team: "std组",
    type: "type1",
  },
  136: {
    members: "谢弘宇、郑力嘉、黄志豪",
    school: "华东理工大学",
    team: "华理小伙",
    type: "type2 unofficial",
  },
  137: {
    members: "姜中为、逯天毅、王效涛",
    school: "华东理工大学",
    team: "上课铃是摇篮曲所以我们11点就下线",
    type: "type1",
  },
  138: {
    members: "刘天瑞、高祖阳、王磊",
    school: "华东师范大学",
    team: "饮茶先啦",
    type: "type1",
  },
  139: {
    members: "张洋、王叶伟、荣思齐",
    school: "华南理工大学",
    team: "队友贸易协会",
    type: "type1",
  },
  140: {
    members: "李珲、钱晨炼、冼昊明",
    school: "华南理工大学",
    team: "胖头鱼头胖",
    type: "type1",
  },
  141: {
    members: "林汇、徐奕标、罗泽华",
    school: "华南农业大学",
    team: "绘夏之色",
    type: "type1",
  },
  142: {
    members: "冼嘉荣、陈泽勇、杨方安",
    school: "华南师范大学",
    team: "ccpc观光队",
    type: "type1",
  },
  143: {
    members: "罗佳玲、刘其琦、傅绍基",
    school: "华南师范大学",
    team: "wa掘机",
    type: "type1",
  },
  144: {
    members: "马晖凯、刘文恒、朱家明",
    school: "华南师范大学",
    team: "码大忍下",
    type: "type2 unofficial",
  },
  145: {
    members: "关竣佑、覃醒亮、陈鹏宇",
    school: "华南师范大学",
    team: "删库跑路",
    type: "type2 unofficial",
  },
  146: {
    members: "何智聪、余得绪、容加林",
    school: "华南师范大学",
    team: "学不会，怎么想都学不会",
    type: "type1",
  },
  147: {
    members: "陈首翱、张天翼、姜宇琦",
    school: "华中师范大学",
    team: "姜子翼子翱子",
    type: "type1",
  },
  148: {
    members: "张珉玮、郑仕佳、李薪",
    school: "惠州学院",
    team: "三个碳基生物",
    type: "type2 unofficial",
  },
  149: {
    members: "符智基、张仲轩、陈欣然",
    school: "惠州学院",
    team: "绽华之刻",
    type: "type1",
  },
  150: {
    members: "陈铭豪、黄昌盛、李光赫",
    school: "吉林大学",
    team: "柴郡猫猫QuQ",
    type: "type1",
  },
  151: {
    members: "过思齐、陈泽祺、王品欢",
    school: "吉林大学",
    team: "世末鸽者",
    type: "type1",
  },
  152: {
    members: "周宇恒、陈瀚、高钧",
    school: "吉林大学",
    team: "要fast不要fst",
    type: "type1",
  },
  153: {
    members: "吴钿俊、黎子龙、易松杰",
    school: "吉首大学",
    team: "我是谁？大本钟",
    type: "type1",
  },
  154: {
    members: "刘延松、刘垚、闫洪宇",
    school: "济南大学",
    team: "骨钉小师 2.0",
    type: "type2 unofficial",
  },
  155: {
    members: "张益铭、林晨、王征宇",
    school: "济南大学",
    team: "轩昂",
    type: "type1",
  },
  156: {
    members: "范淮宝、陈雪武、杨琇婷",
    school: "嘉应学院",
    team: "吃饭不张口",
    type: "type1",
  },
  157: {
    members: "颜朝杰、蔡创昇、袁锐涛",
    school: "嘉应学院",
    team: "蒻鸡萌新",
    type: "type2 unofficial",
  },
  158: {
    members: "赖清林、罗颖博、李鑫涛",
    school: "江西理工大学",
    team: "1敲2想3端茶",
    type: "type1",
  },
  159: {
    members: "朱金康、郑恒庆、邓英豪",
    school: "江西理工大学",
    team: "玖曦",
    type: "type2 unofficial",
  },
  160: {
    members: "朱宴辉、张永新、赵辰",
    school: "辽宁工程技术大学",
    team: "全都AC全都过",
    type: "type1",
  },
  161: {
    members: "毛永杰、王永发、柳聪",
    school: "辽宁工程技术大学",
    team: "全靠队友AC",
    type: "type1",
  },
  162: {
    members: "孟凡帅、佟佳芮、周钤玺",
    school: "辽宁工程技术大学",
    team: "找不到",
    type: "type1",
  },
  163: {
    members: "靳加乐、王铭宇、张丰浩",
    school: "鲁东大学",
    team: "星星之火",
    type: "type1",
  },
  164: {
    members: "唐鑫程、傅俊斌、林俊逸",
    school: "闽南师范大学",
    team: "JV哥哥爱上我",
    type: "type1",
  },
  165: {
    members: "樊能、彭延飞、李长乐",
    school: "南昌大学",
    team: "int mian",
    type: "type1",
  },
  166: {
    members: "潘华成、凌成寿、徐文祥",
    school: "南昌理工学院",
    team: "无情铁首",
    type: "type1",
  },
  167: {
    members: "陈天乐、范磊龙、邹逸凡",
    school: "南方科技大学",
    team: "南方科技大学-巴塞罗那",
    type: "type1",
  },
  168: {
    members: "彭书博、黄弋骞、邓淞航",
    school: "南方科技大学",
    team: "南方科技大学-塞维利亚",
    type: "type1",
  },
  169: {
    members: "贺正、孙瑶、肖正皇",
    school: "南华大学",
    team: "三个代表",
    type: "type1",
  },
  170: {
    members: "陆青阳、杜星语、吴煜青",
    school: "南京大学",
    team: "admax",
    type: "type1",
  },
  171: {
    members: "曹逸中、陈弘毅、邹忠奇",
    school: "南京大学",
    team: "如烟",
    type: "type1",
  },
  172: {
    members: "张兆骞、徐岩心、孙海龙",
    school: "南京航空航天大学",
    team: "拿不到金牌也有女朋友队",
    type: "type1",
  },
  173: {
    members: "袁瑜谦、陆晓兰、张馨予",
    school: "南京航空航天大学",
    team: "匈牙利牛肉焗饭",
    type: "type1",
  },
  174: {
    members: "钱品亦、李亚宁、岑嘉诚",
    school: "南京航空航天大学",
    team: "在CCPC中寻求AC是否搞错了什么？",
    type: "type2 unofficial",
  },
  175: {
    members: "徐杨世杰、王浩宇、蔡佳铭",
    school: "南京理工大学",
    team: "点燃猫猫头",
    type: "type1",
  },
  176: {
    members: "钟涵文、肖冉、赵震",
    school: "南京理工大学",
    team: "好多原批",
    type: "type1",
  },
  177: {
    members: "何乐晗、陈以信、赵一舟",
    school: "南京邮电大学",
    team: "Citrus",
    type: "type1",
  },
  178: {
    members: "宋辰龙、蒋锐、卢雨田",
    school: "南京邮电大学",
    team: "白给队",
    type: "type1",
  },
  179: {
    members: "崔泽昂、郑舜禹、金诚",
    school: "南京邮电大学",
    team: "鸽Prime",
    type: "type1",
  },
  180: {
    members: "罗天辰、郭耘赫、周键钹",
    school: "南开大学",
    team: "南方开心大学",
    type: "type1",
  },
  181: {
    members: "王超星、翟江天、杜岱玮",
    school: "南开大学",
    team: "图一乐",
    type: "type1",
  },
  182: {
    members: "黄子懿、郑原、苑华莹",
    school: "南开大学",
    team: "我没意见",
    type: "type1",
  },
  183: {
    members: "段振威、杨普、万博",
    school: "南阳理工学院",
    team: "队名不能为空",
    type: "type2 unofficial",
  },
  184: {
    members: "陈昊、杨智翔、董雲龙",
    school: "南阳理工学院",
    team: "肥鲶鱼历险记",
    type: "type1",
  },
  185: {
    members: "周静饧、胡宏宇、曹高磊",
    school: "南阳师范学院",
    team: "皮卡皮卡皮卡",
    type: "type1",
  },
  186: {
    members: "安浦聖、窦志宇、贺晨",
    school: "内蒙古农业大学职业技术学院",
    team: "粒子",
    type: "type1",
  },
  187: {
    members: "焦易凡、许博强、黄冠捷",
    school: "齐齐哈尔大学",
    team: "AC很少你忍一下",
    type: "type1",
  },
  188: {
    members: "刘成、徐易、张卫正",
    school: "青岛大学",
    team: "我们想要气球",
    type: "type1",
  },
  189: {
    members: "程泽瑞、曲殊同、王本宇",
    school: "清华大学",
    team: "安全车",
    type: "type1",
  },
  190: {
    members: "王建楠、焦景辉、彭贻豪",
    school: "清华大学",
    team: "焦哥爱喝喜茶",
    type: "type2 unofficial",
  },
  191: {
    members: "刘昀、杨卓毅、宋泽宇",
    school: "清华大学",
    team: "纳豆拌饭",
    type: "type2 unofficial",
  },
  192: {
    members: "陈江伦、李思婷、蒋颸",
    school: "清华大学",
    team: "三只狗狗",
    type: "type1",
  },
  193: {
    members: "韩麒鸿、陈奕州、石伟宁",
    school: "厦门大学",
    team: "羽未炒饭",
    type: "type1",
  },
  194: {
    members: "吴新宇、吴志伟、杨骏飞",
    school: "厦门大学嘉庚学院",
    team: "这白开水没有味",
    type: "type1",
  },
  195: {
    members: "王在烜、周何、卢子辰",
    school: "山东大学",
    team: "樱花猪开喵喵车创大白熊",
    type: "type1",
  },
  196: {
    members: "周鑫、严一涵、宣启楠",
    school: "山东大学（威海）",
    team: "队名已冻结",
    type: "type1",
  },
  197: {
    members: "孙天琦、庄昊霖、陈龙泽",
    school: "山东大学（威海）",
    team: "你这AC挺能藏",
    type: "type1",
  },
  198: {
    members: "赵兴锐、穆俊霖、方恺鹏",
    school: "山东理工大学",
    team: "今天拿铁半价",
    type: "type1",
  },
  199: {
    members: "李威翰、苌锦煦、张元帅",
    school: "山东理工大学",
    team: "这发必过",
    type: "type2 unofficial",
  },
  200: {
    members: "李浩然、王欣、蓝宗慰",
    school: "山东师范大学",
    team: "快攻猛男",
    type: "type1",
  },
  201: {
    members: "秦云啸、陈安格、唐笑涵",
    school: "上海大学",
    team: "代码写的都队",
    type: "type2 unofficial",
  },
  202: {
    members: "金霆峰、李梓航、黄浩",
    school: "上海大学",
    team: "哈尔滨不冷吗",
    type: "type1",
  },
  203: {
    members: "郑清锋、周天澜、金之谦",
    school: "上海大学",
    team: "行星",
    type: "type1",
  },
  204: {
    members: "李凯麟、徐正阳、易兰萱",
    school: "上海大学",
    team: "荒原",
    type: "type1",
  },
  205: {
    members: "施安然、史佳朋、胡赫宇",
    school: "上海大学",
    team: "黄昏",
    type: "type2 unofficial",
  },
  206: {
    members: "刘思聪、罗晨轩、谢华",
    school: "上海大学",
    team: "一编就对",
    type: "type2 unofficial",
  },
  207: {
    members: "阮航、方俊杰、肖景琦",
    school: "上海交通大学",
    team: "少年游",
    type: "type1",
  },
  208: {
    members: "何开、李文超、龚可",
    school: "上海科技大学",
    team: "未来道具研究所",
    type: "type1",
  },
  209: {
    members: "曹宇涵、彭程、赵清澄",
    school: "上海科技大学",
    team: "我们转数院吧",
    type: "type1",
  },
  210: {
    members: "郭泽森、苏梓瀚、陈俊明",
    school: "深圳大学",
    team: "SZU-Archimedes",
    type: "type1",
  },
  211: {
    members: "费楚雯、齐宇轩、陈希哲",
    school: "深圳大学",
    team: "SZU-YanranLee",
    type: "type1",
  },
  212: {
    members: "韦古峰、王梓睿、张祺",
    school: "沈阳化工大学",
    team: "关于队友全是rand()跑出来的这件事",
    type: "type1",
  },
  213: {
    members: "徐池、宋世鹏、李思成",
    school: "石家庄铁道大学",
    team: "ssp的航空母舰",
    type: "type1",
  },
  214: {
    members: "楚博然、王耀、杨雨豪",
    school: "四川大学",
    team: "“机械化就输不了”",
    type: "type1",
  },
  215: {
    members: "张新、向宇、朱奕杰",
    school: "四川大学",
    team: "鴏麚斖縩韠",
    type: "type1",
  },
  216: {
    members: "于立恒、陆佳浩、王志庞",
    school: "苏州大学",
    team: "渐入'佳'境",
    type: "type1",
  },
  217: {
    members: "王雨、孙楠、汤添文",
    school: "苏州大学",
    team: "喷射战士",
    type: "type1",
  },
  218: {
    members: "黄学文、许睿阳、唐瑞珑",
    school: "苏州大学",
    team: "气球多多",
    type: "type2 unofficial",
  },
  219: {
    members: "潘骏炜、王彦柏、蔡博凯",
    school: "苏州大学",
    team: "三人成行",
    type: "type2 unofficial",
  },
  220: {
    members: "刘璞、刘瑞祺、张千",
    school: "唐山学院",
    team: "雁字回时",
    type: "type1",
  },
  221: {
    members: "杜鼎勋、何志凌、张博凯",
    school: "天津大学",
    team: "树状数组维护01背包",
    type: "type1",
  },
  222: {
    members: "王彦淞、谢天驰、刘睿",
    school: "天津大学",
    team: "五个小时怎么就这么紧呢",
    type: "type1",
  },
  223: {
    members: "杨磊、冯会东、唐小钰",
    school: "天津工业大学",
    team: "专注分母二十年",
    type: "type1",
  },
  224: {
    members: "陈佳博、罗耀宇、向东",
    school: "天津理工大学",
    team: "打铁还需自身硬",
    type: "type1",
  },
  225: {
    members: "徐正扬、谢泽邦、储岱泽",
    school: "同济大学",
    team: "代码补全计划",
    type: "type2 unofficial",
  },
  226: {
    members: "张迪、庞鹏瞩、高天宸",
    school: "同济大学",
    team: "快乐面具",
    type: "type1",
  },
  227: {
    members: "柳慧林、赵建泉、张开元",
    school: "潍坊学院",
    team: "xx短发天下第一",
    type: "type1",
  },
  228: {
    members: "常毅威、周思豪、石杨涛",
    school: "武昌理工学院",
    team: "浅川树",
    type: "type1",
  },
  229: {
    members: "杨之典、向雅欣、林蒙",
    school: "武汉大学",
    team: "坏了。怎么取名。没有想法。",
    type: "type1",
  },
  230: {
    members: "吴雨欣、郑亮涛、韦弘杨",
    school: "武汉大学",
    team: "疲倦且内卷",
    type: "type1",
  },
  231: {
    members: "万宇恒、苏禹畅、林锟扬",
    school: "武汉大学",
    team: "又睡过了",
    type: "type1",
  },
  232: {
    members: "张亮、柳庆亮、徐震阳",
    school: "武汉纺织大学",
    team: "梦之队",
    type: "type1",
  },
  233: {
    members: "方铭、徐泽宇、许泽旺",
    school: "武汉工程大学",
    team: "wityyds",
    type: "type2 unofficial",
  },
  234: {
    members: "刘典、罗云祥、符轩豪",
    school: "武汉工程大学",
    team: "雀食蟀",
    type: "type1",
  },
  235: {
    members: "王印德、翁锦瑞、王忠齐",
    school: "武汉科技大学",
    team: "呐，你也想要KiraKira吗？",
    type: "type1",
  },
  236: {
    members: "张杰、李佳毅、陈一凡",
    school: "武汉科技大学",
    team: "有人四级没过",
    type: "type1",
  },
  237: {
    members: "张力云、王言聪、刘工锟",
    school: "西安电子科技大学",
    team: "暴交cheer不舍",
    type: "type2 unofficial",
  },
  238: {
    members: "谭升阳、谢铭松、郭浩杰",
    school: "西安电子科技大学",
    team: "布鲁特福斯惊呼内行",
    type: "type1",
  },
  239: {
    members: "陈德创、冯瑞森、祝君超",
    school: "西安电子科技大学",
    team: "慢慢来_",
    type: "type2 unofficial",
  },
  240: {
    members: "蒋叶桢、曾祥翼、张炀杰",
    school: "西安电子科技大学",
    team: "转眼间又在下雨",
    type: "type1",
  },
  241: {
    members: "唐梓航、赵宋文、陈执镇",
    school: "西安交通大学",
    team: "我们还行吧？那当然",
    type: "type1",
  },
  242: {
    members: "孙乔、吴晨宇、曹成伟",
    school: "西北大学",
    team: "驼鹿行动",
    type: "type1",
  },
  243: {
    members: "曾豪、李喆元、黄意雯",
    school: "西北工业大学",
    team: "名额自动机",
    type: "type1",
  },
  244: {
    members: "管孙笛、汪梁森、金煜峰",
    school: "西北工业大学",
    team: "心态逐渐平和",
    type: "type1",
  },
  245: {
    members: "徐浩伦、谢清、彭铃",
    school: "西华师范大学",
    team: "西华",
    type: "type1",
  },
  246: {
    members: "郑星宇、李远杰、张未希",
    school: "西南交通大学",
    team: "三元一次方程组",
    type: "type1",
  },
  247: {
    members: "柴艺函、宋昊轩、王翔宇",
    school: "西南交通大学",
    team: "上号！下分！睡觉！",
    type: "type1",
  },
  248: {
    members: "唐振国、李婉儿、黄骏",
    school: "西南民族大学",
    team: "SMU_HRB*",
    type: "type2 unofficial",
  },
  249: {
    members: "张书豪、潘浩霖、李旭东",
    school: "西南民族大学",
    team: "SMU_HRB**",
    type: "type2 unofficial",
  },
  250: {
    members: "张珺开、肖振威、汪湘衡",
    school: "西南民族大学",
    team: "SMU_HRB01",
    type: "type1",
  },
  251: {
    members: "郭青硕、曲恒毅、侯天赐",
    school: "香港中文大学（深圳）",
    team: "可爱天赐摸猫猫",
    type: "type1",
  },
  252: {
    members: "赵国威、刘博、范如杨",
    school: "长春大学",
    team: "要Au而不得",
    type: "type1",
  },
  253: {
    members: "吴仁杰、刘智、王麒景",
    school: "长春工业大学",
    team: "饱食而遨游",
    type: "type1",
  },
  254: {
    members: "李昊霖、张佳琦、杨哲",
    school: "长春工业大学",
    team: "代码不被卡",
    type: "type1",
  },
  255: {
    members: "姜洪正、胡智贤、邢昊然",
    school: "长春工业大学",
    team: "拿铁咖啡",
    type: "type1",
  },
  256: {
    members: "王闯、郭畅、余欢欢",
    school: "长春工业大学",
    team: "逆流而上",
    type: "type2 unofficial",
  },
  257: {
    members: "李金肖、高新桂、朱航",
    school: "长春工业大学",
    team: "人型wa倔机",
    type: "type2 unofficial",
  },
  258: {
    members: "于越、沈吉行、黄宏进",
    school: "长春理工大学",
    team: "普通铁牌",
    type: "type1",
  },
  259: {
    members: "熊谦、刘群、肖芊芊",
    school: "长沙理工大学",
    team: "霸道数学爱上我",
    type: "type1",
  },
  260: {
    members: "潘劲帆、章晨榆、钟天宇",
    school: "浙大城市学院",
    team: "来杯拿铁",
    type: "type1",
  },
  261: {
    members: "翁茹芸、余建赛、吴亦初",
    school: "浙大宁波理工学院",
    team: "随机应变",
    type: "type1",
  },
  262: {
    members: "劳佳鸿、徐宇诺、张宏剑",
    school: "浙江财经大学",
    team: "读题困难户",
    type: "type1",
  },
  263: {
    members: "龙香遇、陈思睿、王熠",
    school: "浙江大学",
    team: "kswlkswl",
    type: "type1",
  },
  264: {
    members: "彭博、褚写庭、陈逸",
    school: "浙江大学",
    team: "Solitary Dream",
    type: "type1",
  },
  265: {
    members: "徐琪杰、杨予晟、任庭旭",
    school: "浙江大学",
    team: "Supersymmetry Quarkus",
    type: "type1",
  },
  266: {
    members: "樊睿、陈昊旸、盛晨璐",
    school: "浙江大学",
    team: "unshown",
    type: "type1",
  },
  267: {
    members: "郭宇航、张殷杰、俞庄楠",
    school: "浙江工商大学",
    team: "摸鱼组000001",
    type: "type2 unofficial",
  },
  268: {
    members: "毛旦旦、刘政鑫、韩帅彪",
    school: "浙江工商大学",
    team: "且共从容",
    type: "type1",
  },
  269: {
    members: "沈宁、胡泽涛、包淳嘉",
    school: "浙江工业大学",
    team: "ZJUT4",
    type: "type1",
  },
  270: {
    members: "周序、陈传聪、黄圣泽",
    school: "浙江工业大学",
    team: "ZJUT7",
    type: "type1",
  },
  271: {
    members: "张帅威、张会德、陆棒棒",
    school: "浙江金融职业学院",
    team: "《试试水》",
    type: "type2 unofficial",
  },
  272: {
    members: "吴俊杰、吕哲宇、包以琳",
    school: "浙江金融职业学院",
    team: "可持久化内卷",
    type: "type1",
  },
  273: {
    members: "孙寅、尹栋豪、沈序戎",
    school: "浙江科技学院",
    team: "好起来了",
    type: "type1",
  },
  274: {
    members: "宁宇浩、邱天、王显龙",
    school: "浙江理工大学",
    team: "海超人大洋游侠和隐形船",
    type: "type1",
  },
  275: {
    members: "汤丰玮、储炳焘、杨陈真",
    school: "浙江理工大学",
    team: "月下客",
    type: "type1",
  },
  276: {
    members: "杨成艺、任松涛、曾唯策",
    school: "浙江农林大学",
    team: "Aibiyoyo",
    type: "type1",
  },
  277: {
    members: "王子超、陈重喜、陈城",
    school: "浙江农林大学",
    team: "春田花花幼儿园青春版",
    type: "type1",
  },
  278: {
    members: "章扬、邵建皓、丁杭亮",
    school: "浙江农林大学",
    team: "蓼菜成行",
    type: "type2 unofficial",
  },
  279: {
    members: "邓鹏、陈骏鹏、方天笑",
    school: "浙江师范大学",
    team: "出发点",
    type: "type2 unofficial",
  },
  280: {
    members: "王景瑶、滕佳倩、杨佳宁",
    school: "浙江师范大学",
    team: "破铜烂铁",
    type: "type2 unofficial",
  },
  281: {
    members: "丁宇洋、陈靖毅、汤浙栋",
    school: "浙江师范大学",
    team: "人生异或只如初见",
    type: "type1",
  },
  282: {
    members: "叶佳伟、张燮弛、厉文浩",
    school: "浙江师范大学",
    team: "四百四十四点四只狮子",
    type: "type1",
  },
  283: {
    members: "周天辰、余知航、蒋润浩",
    school: "浙江师范大学",
    team: "妖怪被srk转走了QAQ",
    type: "type2 unofficial",
  },
  284: {
    members: "李上鸿、陈高远、翁佳棋",
    school: "浙江育英职业技术学院",
    team: "蜡笔小星",
    type: "type2 unofficial",
  },
  285: {
    members: "温正暖、田若禹、姬梦迪",
    school: "浙江育英职业技术学院",
    team: "田甜圈",
    type: "type2 unofficial",
  },
  286: {
    members: "应佳伟、杨良俊、钱晨乐",
    school: "浙江育英职业技术学院",
    team: "育英六队",
    type: "type2 unofficial",
  },
  287: {
    members: "杨帆、沈钢杰、张翔杰",
    school: "浙江育英职业技术学院",
    team: "育英七队",
    type: "type1",
  },
  288: {
    members: "卢昕怡、钟晓芸、景舒楠",
    school: "浙江中医药大学",
    team: "ZCMU-HTT",
    type: "type2 unofficial",
  },
  289: {
    members: "牛佳慧、王庆康、王少杰",
    school: "浙江中医药大学",
    team: "ZCMU-冲冲冲",
    type: "type2 unofficial",
  },
  290: {
    members: "朱家伟、赵天骏、李弘辰",
    school: "浙江中医药大学",
    team: "ZCMU-聪以知远，明以察微",
    type: "type1",
  },
  291: {
    members: "盛子阳、姚冠宇、毛冬冬",
    school: "浙江中医药大学",
    team: "ZCMU-咩咩咩咩咩",
    type: "type1",
  },
  292: {
    members: "杨宇航、凌鑫、余清扬",
    school: "郑州大学",
    team: "感觉不如线下。。线上",
    type: "type1",
  },
  293: {
    members: "李浩、马少杰、邱宇",
    school: "郑州大学",
    team: "沃特提姆",
    type: "type1",
  },
  294: {
    members: "宋江、张纪龙、张永林",
    school: "郑州轻工业大学",
    team: "la_soleil",
    type: "type1",
  },
  295: {
    members: "刘建顺、张文涛、张佳豪",
    school: "中北大学",
    team: "今朝有牌",
    type: "type1",
  },
  296: {
    members: "冀武韬、柴孟陶、郭锦涛",
    school: "中北大学",
    team: "三tao之队",
    type: "type2 unofficial",
  },
  297: {
    members: "王海深、赵守智、王皓男",
    school: "中北大学",
    team: "无B树-唯AC",
    type: "type1",
  },
  298: {
    members: "张佳鹏、张润齐、车林奇",
    school: "中北大学",
    team: "祝晴",
    type: "type2 unofficial",
  },
  299: {
    members: "亓泽鲁、张华睿、赵润泽",
    school: "中国传媒大学",
    team: "三缺一",
    type: "type1",
  },
  300: {
    members: "易晨竹、刘锦程、王文显",
    school: "中国地质大学（北京）",
    team: "肆零肆",
    type: "type1",
  },
  301: {
    members: "何永鑫、于桐、付欣宇",
    school: "中国地质大学（武汉）",
    team: "背着队友偷偷wa题",
    type: "type1",
  },
  302: {
    members: "曹吉、张迅驰、郭强",
    school: "中国计量大学",
    team: "已经没什么好怕的了",
    type: "type1",
  },
  303: {
    members: "周正谊、陈浩男、林仁豪",
    school: "中国计量大学现代科技学院",
    team: "我的学校真的绿色",
    type: "type1",
  },
  304: {
    members: "沈新迪、王涵斌、朱晨曦",
    school: "中国科学技术大学",
    team: "评测要红过九重",
    type: "type1",
  },
  305: {
    members: "饶恒、王浩博、王泽",
    school: "中国民航大学",
    team: "文明牛魔王想下班",
    type: "type1",
  },
  306: {
    members: "冉桐、傅一笑、李松林",
    school: "中国民航大学",
    team: "做出签到就算成功",
    type: "type2 unofficial",
  },
  307: {
    members: "颜府、谭嘉伟、张展邦",
    school: "中山大学",
    team: "中山大学_零号阵列",
    type: "type1",
  },
  308: {
    members: "黄致博、丘国豪、周伟杰",
    school: "中山大学",
    team: "中山大学_无名",
    type: "type2 unofficial",
  },
  309: {
    members: "陈星辉、方展鸿、陈银超",
    school: "中山大学",
    team: "中山大学-版本答案",
    type: "type1",
  },
  310: {
    members: "邓熙、刘元昊、魏久壹",
    school: "中山大学",
    team: "中山大学-藕粉团子",
    type: "type2 unofficial",
  },
  311: {
    members: "邱煜炜、谢泽辉、张彦博",
    school: "中山大学",
    team: "中山大学-深圳校区没肠粉",
    type: "type1",
  },
  312: {
    members: "陈冠一、田佳渝、邓钰山",
    school: "中山大学",
    team: "中山大学-雪风酱会守护大家的",
    type: "type1",
  },
  313: {
    members: "苏新宇、郭延西、曹大宇",
    school: "重庆邮电大学",
    team: "CCPC Teahouse",
    type: "type1",
  },
  314: {
    members: "王广辉、张靖昆、卢玮杰",
    school: "重庆邮电大学",
    team: "JK47",
    type: "type1",
  },
  315: {
    members: "夏宇、王席、郑立杰",
    school: "山东科技大学（泰安校区）",
    team: "粉红熊",
    type: "type1",
  },
  316: {
    members: "张子戌、李洋彬、张铭韦",
    school: "信息工程大学",
    team: "信大旅游团",
    type: "type1",
  },
  317: {
    members: "李智鹏、于洪洋、黄心庭",
    school: "信息工程大学",
    team: "咱哥说的",
    type: "type2 unofficial",
  },
};
