var teams = {
  1: {
    members: "程晗、胡涵之、常昊冉",
    school: "安徽大学",
    team: "步道乐跑天下第一",
    type: "type1",
  },
  2: {
    members: "晋毓麟、刘庞、石涛",
    school: "安徽科技学院",
    team: "想找人分钱",
    type: "type1",
  },
  3: {
    members: "姜雨竺、张殊睿、蒋季初",
    school: "北京航空航天大学",
    team: "全场最佳观众席",
    type: "type1",
  },
  4: {
    members: "闵家旭、张羿凡、崔绍锞",
    school: "北京航空航天大学",
    team: "沃尔沃夫",
    type: "type1",
  },
  5: {
    members: "邹策、王淇澳、闫阳旭",
    school: "北京化工大学",
    team: "AC自动机",
    type: "type2 unofficial",
  },
  6: {
    members: "李腾飞、陈柯舟、巴衣地力达马木白提",
    school: "北京化工大学",
    team: "听君一席话",
    type: "type1",
  },
  7: {
    members: "洪枢适、曾梓勋、梁凯星",
    school: "北京化工大学",
    team: "自己相似的两性具有",
    type: "type1",
  },
  8: {
    members: "胡越洋、李远铄、缪新宇",
    school: "北京交通大学",
    team: "精妙胡说",
    type: "type1",
  },
  9: {
    members: "邱烨卿、彭彦铭、余彦可",
    school: "北京交通大学",
    team: "万寿无疆",
    type: "type1",
  },
  10: {
    members: "夏旭辉、赵开、刘彦铭",
    school: "北京科技大学",
    team: "不可靠题意传输协议",
    type: "type1",
  },
  11: {
    members: "林恺、朱子林、邹知秋",
    school: "北京理工大学",
    team: "ddl战神",
    type: "type1",
  },
  12: {
    members: "陈鸿韬、李一文、张庚辰",
    school: "北京理工大学",
    team: "ddl战神大战ddl",
    type: "type1",
  },
  13: {
    members: "周楷、邱明亮、张睿敏",
    school: "北京林业大学",
    team: "好潮如评",
    type: "type1",
  },
  14: {
    members: "林靖轩、高艺炜、李明泽",
    school: "北京师范大学",
    team: "内测度",
    type: "type2 unofficial",
  },
  15: {
    members: "赵子豪、徐悦萱、陈婉妍",
    school: "北京师范大学",
    team: "群鸦盛宴",
    type: "type2 unofficial",
  },
  16: {
    members: "王小普、刘语柔、陆春酉",
    school: "北京师范大学",
    team: "网络流",
    type: "type2 unofficial",
  },
  17: {
    members: "吴丽莎、赵建锟、德乐海",
    school: "北京师范大学",
    team: "我说我是乱打的",
    type: "type1",
  },
  18: {
    members: "彭泊词、汤昕宇、卢炜文",
    school: "北京师范大学",
    team: "谢谢卡尔",
    type: "type1",
  },
  19: {
    members: "蔡仲勋、王昱超、张民轩",
    school: "北京师范大学珠海校区",
    team: "不爆零就算成功",
    type: "type2 unofficial",
  },
  20: {
    members: "刘雨杭、姚梦俊、刘东轩",
    school: "北京师范大学珠海校区",
    team: "公费旅游团？不可能的",
    type: "type1",
  },
  21: {
    members: "刘泽昊、宋开元、苏永鑫",
    school: "北京信息科技大学",
    team: "走到湖边就会哈拉一下买一杯美式",
    type: "type1",
  },
  22: {
    members: "汤子唯、董凯文、高畅",
    school: "北京邮电大学",
    team: "NMLPC",
    type: "type2 unofficial",
  },
  23: {
    members: "董建威、雍梓奇、谢国富",
    school: "北京邮电大学",
    team: "不带走一个气球",
    type: "type1",
  },
  24: {
    members: "刘涛、范珈诚、段锦宇",
    school: "北京邮电大学",
    team: "鸿蒙",
    type: "type1",
  },
  25: {
    members: "王佳禾、张天泽、区庆亮",
    school: "北京邮电大学",
    team: "三只蒟蒻",
    type: "type1",
  },
  26: {
    members: "徐柔、张雷、詹智航",
    school: "常熟理工学院",
    team: "拿不拿奖队长都女装",
    type: "type1",
  },
  27: {
    members: "张政宇、梁俊尚、闫学城",
    school: "成都理工大学",
    team: "二仙桥恐龙队",
    type: "type1",
  },
  28: {
    members: "余春生、王星辰、李梓靖",
    school: "成都信息工程大学",
    team: "我想带两个小妹妹",
    type: "type1",
  },
  29: {
    members: "黄承诺、蔡廷漳、濮凡轶",
    school: "大连理工大学",
    team: "时间逆旅者",
    type: "type1",
  },
  30: {
    members: "赖哲剑、刘政、吴稼宇",
    school: "大连理工大学",
    team: "终于出来旅游了",
    type: "type1",
  },
  31: {
    members: "黄龙、张济麟、吴培涛",
    school: "成都中医药大学",
    team: "以上队伍全部作废",
    type: "type1",
  },
  32: {
    members: "郝益民、王浩舟、郑皓瑞",
    school: "电子科技大学",
    team: "空气人",
    type: "type1",
  },
  33: {
    members: "弋竞为、喻鹏云、周湘阳",
    school: "电子科技大学",
    team: "膜法少女",
    type: "type1",
  },
  34: {
    members: "杨登庆、刘阳依健、黎婷",
    school: "电子科技大学",
    team: "喜欢看叔",
    type: "type1",
  },
  35: {
    members: "刘泽铭、吴一玄、罗潇阳",
    school: "东北大学秦皇岛分校",
    team: "GNK48-101",
    type: "type1",
  },
  36: {
    members: "张烨槟、张逸凡、沈晓汐",
    school: "东北大学秦皇岛分校",
    team: "就这场了",
    type: "type1",
  },
  37: {
    members: "胡鸿捷、刘琛、袁茂恒",
    school: "东北大学秦皇岛分校",
    team: "升空的奖牌，从台下看还是台上看？",
    type: "type1",
  },
  38: {
    members: "唐瑀佳、李兴锐、路号号",
    school: "东北农业大学",
    team: "不差这二十分钟",
    type: "type1",
  },
  39: {
    members: "童浩龙、徐文浩、唐佳成",
    school: "东北师范大学",
    team: "长夜漫漫",
    type: "type1",
  },
  40: {
    members: "郑祎凡、潘景瑞、戚雨林",
    school: "东南大学",
    team: "猛犸不上ban",
    type: "type1",
  },
  41: {
    members: "郭少强、林毅祥、黄朝英",
    school: "福建工程学院",
    team: "广州人别吃福建人",
    type: "type1",
  },
  42: {
    members: "兰宇平、林新煜、郑一凡",
    school: "福建农林大学",
    team: "诶嘿",
    type: "type1",
  },
  43: {
    members: "余镐、陈昊旸、苏锦程",
    school: "福州大学",
    team: "企鹅人大战谜语人",
    type: "type1",
  },
  44: {
    members: "李诺凡、田剑心、欧云帆",
    school: "福州大学",
    team: "签到五分钟罚坐四小时",
    type: "type1",
  },
  45: {
    members: "谢天意、谢腾飞、储思晴",
    school: "阜阳师范大学",
    team: "我就想拿个牌儿",
    type: "type1",
  },
  46: {
    members: "聂绍珩、程鹏志、梁敬聪",
    school: "复旦大学",
    team: "冰泮北徂",
    type: "type1",
  },
  47: {
    members: "高庆麾、陆佳艺、刘明君",
    school: "复旦大学",
    team: "莱布尼兹惊坐起",
    type: "type2 unofficial",
  },
  48: {
    members: "阮毅凡、杜雨轩、吴可非",
    school: "复旦大学",
    team: "上海爱丽丝幻乐团",
    type: "type1",
  },
  49: {
    members: "蔡普凡、朱钦瀚、刘恒利",
    school: "广东财经大学",
    team: "忘了她我们一起打CCPC",
    type: "type1",
  },
  50: {
    members: "张惠龙、郑旭、范德川",
    school: "广东东软学院",
    team: "WA哈哈",
    type: "type1",
  },
  51: {
    members: "柯新宇、张海庭、段环宇",
    school: "广东工业大学",
    team: "简单爆零",
    type: "type1",
  },
  52: {
    members: "梁卓楠、梁泽丰、钟浩彬",
    school: "广东工业大学",
    team: "沸水",
    type: "type1",
  },
  53: {
    members: "杨泓亮、刘禹初、詹理涵",
    school: "广东外语外贸大学",
    team: "我们就快要赢了不是吗",
    type: "type1",
  },
  54: {
    members: "金珉瑞、蓝秋雨、阮慧鹏",
    school: "广西大学",
    team: "分母跃龙门当分子队",
    type: "type1",
  },
  55: {
    members: "王利明、武成志、陈嘉怡",
    school: "广西大学",
    team: "赶着报名",
    type: "type1",
  },
  56: {
    members: "李欣燃、麻庭豪、陈昌浩",
    school: "广西科技大学",
    team: "守护最好的猫猫星",
    type: "type1",
  },
  57: {
    members: "资颖泉、黄永雄、张文亮",
    school: "广西师范大学",
    team: "师大米粉",
    type: "type1",
  },
  58: {
    members: "陈一恺、陈宏营、何镓乐",
    school: "广州城市理工学院",
    team: "《关于fufu只想湿法炼铜的这件事》",
    type: "type1",
  },
  59: {
    members: "黄海鑫、邱梓逸、梁导懿",
    school: "广州软件学院",
    team: "迦希女王不会放弃",
    type: "type1",
  },
  60: {
    members: "曾凯恩、姚灏坤、莫日锋",
    school: "广州软件学院",
    team: "快进到AC",
    type: "type1",
  },
  61: {
    members: "林国旺、汤广桉、吴伟俊",
    school: "广州大学",
    team: "火树琪花",
    type: "type1",
  },
  62: {
    members: "鲁智昊、周博睿、王鹏程",
    school: "桂林电子科技大学",
    team: "罚时不到两位数就算大成功",
    type: "type1",
  },
  63: {
    members: "宁申恺、苏一水、李立",
    school: "桂林电子科技大学",
    team: "广西小清华",
    type: "type1",
  },
  64: {
    members: "刘思语、汪庭浩、黄思晨",
    school: "桂林电子科技大学",
    team: "无名之辈",
    type: "type1",
  },
  65: {
    members: "陈星宇、彭鸿祥、张钰敏",
    school: "桂林电子科技大学",
    team: "一队软萌的对手",
    type: "type1",
  },
  66: {
    members: "亢世嘉、吴佳英、左传奇",
    school: "国防科技大学",
    team: "自然选择号",
    type: "type1",
  },
  67: {
    members: "郭彬、伍凌雲、郭嘉梁",
    school: "哈尔滨工程大学",
    team: "ACorWA这是个问题",
    type: "type1",
  },
  68: {
    members: "杨佳霖、徐子涵、彭金浩",
    school: "哈尔滨工程大学",
    team: "AlleXceed Familia",
    type: "type1",
  },
  69: {
    members: "杨春昊、黄凯鹏、李林轩",
    school: "哈尔滨工程大学",
    team: "HEU114514队",
    type: "type1",
  },
  70: {
    members: "周智、常一帆、管袁菲",
    school: "哈尔滨工程大学",
    team: "人菜瘾大",
    type: "type1",
  },
  71: {
    members: "唐贝利、颜伟业、杨林翰",
    school: "哈尔滨工业大学",
    team: "奥赛罗",
    type: "type1",
  },
  72: {
    members: "王子恺、王梓尧、徐琬",
    school: "哈尔滨工业大学",
    team: "明日夜空哨戒班",
    type: "type1",
  },
  73: {
    members: "王晓亮、徐放、金义扬",
    school: "哈尔滨工业大学",
    team: "三维半布丁交",
    type: "type1",
  },
  74: {
    members: "沈文、潘思成、曹杨",
    school: "哈尔滨工业大学（深圳）",
    team: "骗分大队",
    type: "type1",
  },
  75: {
    members: "梁珊、任秦江、卢郡然",
    school: "哈尔滨工业大学（深圳）",
    team: "删库跑路",
    type: "type1",
  },
  76: {
    members: "解裕懋、曹瑞宁、戚煜",
    school: "哈尔滨工业大学（威海）",
    team: "队友打的都队",
    type: "type1",
  },
  77: {
    members: "刘梓竣、孙皓宇、王子康",
    school: "哈尔滨工业大学（威海）",
    team: "青州街幼儿园",
    type: "type1",
  },
  78: {
    members: "陈秋宇、安龙浩、高佳乐",
    school: "哈尔滨工业大学（威海）",
    team: "球达不溜球",
    type: "type1",
  },
  79: {
    members: "庄子晨、汪明曌、赖科华",
    school: "哈尔滨理工大学",
    team: "哈理工12队",
    type: "type1",
  },
  80: {
    members: "陆泓宇、李伟松、马梓豪",
    school: "韩山师范学院",
    team: "玫瑰常开警告常在",
    type: "type1",
  },
  81: {
    members: "余智超、姜正、潘思成",
    school: "杭州电子科技大学",
    team: "杭电2021-16队",
    type: "type1",
  },
  82: {
    members: "汤丰瑜、郑凯心、侯津涛",
    school: "杭州电子科技大学",
    team: "杭电2021-1队",
    type: "type1",
  },
  83: {
    members: "符振皓、张浩杨、彭崟",
    school: "杭州电子科技大学",
    team: "杭电2021-7队",
    type: "type1",
  },
  84: {
    members: "毛一枭、王权、来毅超",
    school: "杭州电子科技大学信息工程学院",
    team: "胜机",
    type: "type1",
  },
  85: {
    members: "邵铁夫、温声荣、苏桐渤",
    school: "杭州师范大学",
    team: "Fahaxiki",
    type: "type1",
  },
  86: {
    members: "俞家豪、严家俊、吴宪",
    school: "杭州师范大学",
    team: "她只是我的妹妹",
    type: "type1",
  },
  87: {
    members: "姜万磊、何昕悦、胡代金",
    school: "合肥工业大学宣城校区",
    team: "跑快快",
    type: "type1",
  },
  88: {
    members: "马云龙、兰锐、胡辰阳",
    school: "合肥学院",
    team: "你一定要喊吗",
    type: "type1",
  },
  89: {
    members: "华征豪、马钰鹏、林锦东",
    school: "河北大学",
    team: "河北大学云帆",
    type: "type1",
  },
  90: {
    members: "康玮琦、杨占宇、曲浩禹",
    school: "河北师范大学",
    team: "欧尼酱daisikei",
    type: "type1",
  },
  91: {
    members: "王竞同、赵崇文、陈语奇",
    school: "河海大学",
    team: "布丁的线段树",
    type: "type1",
  },
  92: {
    members: "蒋子俊、邓伦、占羽淳",
    school: "河海大学",
    team: "几丁质",
    type: "type1",
  },
  93: {
    members: "许金龙、李晨龙、张承树",
    school: "河南工业大学",
    team: "君问归期未有期",
    type: "type1",
  },
  94: {
    members: "陈宗朋、付文军、刘卓芸",
    school: "黑龙江大学",
    team: "面向Accept程序设计",
    type: "type1",
  },
  95: {
    members: "韦放、黄家旺、陈增一",
    school: "湖南大学",
    team: "困难户",
    type: "type1",
  },
  96: {
    members: "苏杰、张聪懿、吴天",
    school: "湖南大学",
    team: "歪比歪比歪比巴卜",
    type: "type1",
  },
  97: {
    members: "谭晓洋、左国祥、王海",
    school: "湖南警察学院",
    team: "今天你AC了吗",
    type: "type1",
  },
  98: {
    members: "关鑫、傅嘉、侯润龙",
    school: "湖南科技大学",
    team: "不上班的猛犸",
    type: "type1",
  },
  99: {
    members: "秦豪远、周子盛、陈思源",
    school: "湖南科技大学",
    team: "代码奔腾",
    type: "type1",
  },
  100: {
    members: "王鼎、李云帆、王子涵",
    school: "华东师范大学",
    team: "布朗尼",
    type: "type1",
  },
  101: {
    members: "洪鹏培、张亮、王一帆",
    school: "华南理工大学",
    team: "CSP-J入门组",
    type: "type1",
  },
  102: {
    members: "谢文拯、陈漫璟、余梓灏",
    school: "华南理工大学",
    team: "都市弃少",
    type: "type1",
  },
  103: {
    members: "陈国昊、赵冬青、梁耀威",
    school: "华南理工大学",
    team: "快乐一轮游",
    type: "type1",
  },
  104: {
    members: "黄俊鸿、赖兴、林俊杨",
    school: "华南农业大学",
    team: "ACM就是要啸着打",
    type: "type1",
  },
  105: {
    members: "许智友、庄鑫耿、周俊尧",
    school: "华南农业大学",
    team: "热恋期的尧尧",
    type: "type1",
  },
  106: {
    members: "赵雨扬、徐聪、郑量",
    school: "华侨大学",
    team: "红日初升",
    type: "type1",
  },
  107: {
    members: "李扬天、唐继民、章万扬",
    school: "华中科技大学",
    team: "从0开始的acmer生活",
    type: "type1",
  },
  108: {
    members: "贺继尧、沈奥成、俞仲遥",
    school: "华中科技大学",
    team: "开脑瓜的小火车",
    type: "type1",
  },
  109: {
    members: "罗广波、匡智颉、陈宇昂",
    school: "华中科技大学",
    team: "提前下班",
    type: "type1",
  },
  110: {
    members: "陈首翱、张天翼、姜宇琦",
    school: "华中师范大学",
    team: "姜子翼子翱子",
    type: "type1",
  },
  111: {
    members: "刘一泓、刘政、胡婧",
    school: "华中师范大学",
    team: "我被逐出队伍后过上社畜生活",
    type: "type1",
  },
  112: {
    members: "陈铭豪、黄昌盛、李光赫",
    school: "吉林大学",
    team: "柴郡猫猫QuQ",
    type: "type1",
  },
  113: {
    members: "过思齐、陈泽祺、王品欢",
    school: "吉林大学",
    team: "世末鸽者",
    type: "type1",
  },
  114: {
    members: "周宇恒、陈瀚、高钧",
    school: "吉林大学",
    team: "要fast不要fst",
    type: "type1",
  },
  115: {
    members: "江小举、黄勋、何皆庆",
    school: "集美大学",
    team: "我们不会修电脑",
    type: "type1",
  },
  116: {
    members: "张益铭、林晨、王征宇",
    school: "济南大学",
    team: "轩昂",
    type: "type1",
  },
  117: {
    members: "严晗、江泽凯、林泽生",
    school: "暨南大学",
    team: "罚时自动机",
    type: "type1",
  },
  118: {
    members: "柯瑞凯、阮炜霖、陈沛恩",
    school: "暨南大学",
    team: "正十字",
    type: "type1",
  },
  119: {
    members: "麦骏、文荫华、温键伟",
    school: "暨南大学",
    team: "追光者",
    type: "type1",
  },
  120: {
    members: "魏宇非、陈少聪、陈云豪",
    school: "江南大学",
    team: "星辰大海",
    type: "type1",
  },
  121: {
    members: "陈康、邱熠、陈力",
    school: "江西师范大学",
    team: "去北京泡脚",
    type: "type1",
  },
  122: {
    members: "胡文豪、宋佑祺、田震雄",
    school: "江西师范大学",
    team: "我的二叉树被淹了",
    type: "type1",
  },
  123: {
    members: "邵江涛、陶璐、胡明涛",
    school: "金华职业技术学院",
    team: "未定义",
    type: "type1",
  },
  124: {
    members: "盛夏滔、范林赟、周煜斌",
    school: "金陵科技学院",
    team: "布洛特亨德尔",
    type: "type1",
  },
  125: {
    members: "殷俊杰、张峰、李蕴杰",
    school: "金陵科技学院",
    team: "血压太高控制不住怎么办",
    type: "type1",
  },
  126: {
    members: "李文凯、孟思宇、水源",
    school: "兰州大学",
    team: "真没睡",
    type: "type1",
  },
  127: {
    members: "吕孟霖、周猛、李汶涛",
    school: "乐山师范学院",
    team: "wa楼上wa楼下",
    type: "type2 unofficial",
  },
  128: {
    members: "熊四莘、赵泽柱、钟闻杰",
    school: "乐山师范学院",
    team: "猪猪恶霸的哥哥",
    type: "type1",
  },
  129: {
    members: "殷勇杰、雷震宇、阎坷凡",
    school: "辽宁大学",
    team: "宵待雨月",
    type: "type1",
  },
  130: {
    members: "沈文渊、吴衍涛、周明跃",
    school: "鲁东大学",
    team: "莫比乌斯环",
    type: "type1",
  },
  131: {
    members: "陈龙、谭利洁、韩艺松",
    school: "闽南科技学院",
    team: "爱会消失对不队",
    type: "type1",
  },
  132: {
    members: "唐鑫程、傅俊斌、林俊逸",
    school: "闽南师范大学",
    team: "JV哥哥爱上我",
    type: "type1",
  },
  133: {
    members: "周珈伊、董廷臻、陈浩然",
    school: "南方科技大学",
    team: "南方科技大学-马德里",
    type: "type2 unofficial",
  },
  134: {
    members: "水兵、陈元旻、蒋潇鹏",
    school: "南京大学",
    team: "烂飞机",
    type: "type1",
  },
  135: {
    members: "陈政弛、王宇峣、刘响",
    school: "南京大学",
    team: "六只手都在摸鱼",
    type: "type1",
  },
  136: {
    members: "丁天行、单启程、欧丰宁",
    school: "南京大学",
    team: "虚幻黄昏",
    type: "type1",
  },
  137: {
    members: "沈凌翔、吴家庆、晏开文",
    school: "南京航空航天大学",
    team: "我全都要",
    type: "type1",
  },
  138: {
    members: "陈涣焕、金朝哲、郭佳樊",
    school: "南京理工大学",
    team: "逆转猫猫头",
    type: "type1",
  },
  139: {
    members: "郑镐予、周怿翔、马维龙",
    school: "南京林业大学",
    team: "拜托了，另一个我",
    type: "type1",
  },
  140: {
    members: "陈泳琦、杨可、陈超然",
    school: "南京信息工程大学",
    team: "专业防爆零",
    type: "type1",
  },
  141: {
    members: "黄锦宇、吴思余、马青宇",
    school: "南京邮电大学",
    team: "饥饿的时候没有创造力",
    type: "type1",
  },
  142: {
    members: "张帅青、刁煜凡、陈煜阳",
    school: "南京邮电大学",
    team: "事末鸽者",
    type: "type1",
  },
  143: {
    members: "叶盛、苏展、季炎",
    school: "南通大学",
    team: "NTU1",
    type: "type1",
  },
  144: {
    members: "马春粮、付静永、田富浩",
    school: "内蒙古电子信息职业技术学院",
    team: "焦糖d瓜",
    type: "type1",
  },
  145: {
    members: "张泽兴、韩步青、于宏悦",
    school: "内蒙古师范大学",
    team: "Au Copper Medal",
    type: "type1",
  },
  146: {
    members: "赵文浩、梁甜甜、马鸿飞",
    school: "内蒙古师范大学",
    team: "这次一定",
    type: "type1",
  },
  147: {
    members: "李然、孙运泽、王天宇",
    school: "青岛大学",
    team: "随便打打都",
    type: "type1",
  },
  148: {
    members: "朱悦宁、慎梓戎、曹歆蕤",
    school: "清华大学",
    team: "黑化肥会发灰",
    type: "type1",
  },
  149: {
    members: "夏天睿、郎思轲、姜迅驰",
    school: "清华大学",
    team: "三杯两盏咸酒",
    type: "type1",
  },
  150: {
    members: "高嘉煊、颜杰龙、王之栋",
    school: "清华大学",
    team: "粤粤欲试",
    type: "type1",
  },
  151: {
    members: "徐浩楠、徐玮嘉、李浩",
    school: "宁波大学",
    team: "超级BUG创作家",
    type: "type1",
  },
  152: {
    members: "陈佳乐、施维康、张自力",
    school: "泉州师范学院",
    team: "ac再爱我亿次",
    type: "type1",
  },
  153: {
    members: "范徐伟、罗意凡、喻越",
    school: "厦门大学嘉庚学院",
    team: "顺心糖",
    type: "type1",
  },
  154: {
    members: "王在烜、周何、卢子辰",
    school: "山东大学",
    team: "樱花猪开喵喵车创大白熊",
    type: "type1",
  },
  155: {
    members: "赵兴锐、穆俊霖、方恺鹏",
    school: "山东理工大学",
    team: "今天拿铁半价",
    type: "type1",
  },
  156: {
    members: "董鑫、王硕、张航",
    school: "山东理工大学",
    team: "小蛋糕",
    type: "type2 unofficial",
  },
  157: {
    members: "黄哲凯、潘锦华、张健",
    school: "汕头大学",
    team: "汕大冲冲冲",
    type: "type1",
  },
  158: {
    members: "徐京伟、阮健乘、刘伊阳",
    school: "上海大学",
    team: "白洞",
    type: "type1",
  },
  159: {
    members: "程天豪、蔡尤帅、李想",
    school: "上海大学",
    team: "纳什米尔",
    type: "type1",
  },
  160: {
    members: "李奕帆、邓馨、张雨奇",
    school: "上海大学",
    team: "运行时出错",
    type: "type1",
  },
  161: {
    members: "胡小川、吴宇轩、洪一芃",
    school: "上海海事大学",
    team: "崩坏永存",
    type: "type1",
  },
  162: {
    members: "尹良升、张骋楷、杨晋晟",
    school: "上海交通大学",
    team: "从百草园到三味书屋",
    type: "type1",
  },
  163: {
    members: "杨宗翰、杨尚霏、谭博仁",
    school: "上海交通大学",
    team: "洒满黄浦江",
    type: "type1",
  },
  164: {
    members: "潘孝安、王驭洋、胡洁昌",
    school: "上海理工大学",
    team: "令和三年的上海爱丽丝",
    type: "type1",
  },
  165: {
    members: "林世奕、沈睿祺、张驰",
    school: "上海师范大学",
    team: "彭总让我们改个好听的队名",
    type: "type1",
  },
  166: {
    members: "刘仟华、钟兆雄、苏嘉淇",
    school: "深圳大学",
    team: "SZU-Linus",
    type: "type1",
  },
  167: {
    members: "徐嘉辉、吴雨恒、施支林",
    school: "深圳技术大学",
    team: "掷骰子",
    type: "type1",
  },
  168: {
    members: "毕之语、郭利民、张中辉",
    school: "四川大学",
    team: "你下载国家反诈中心app了吗",
    type: "type1",
  },
  169: {
    members: "顾曦骏、谭茜匀、詹宜瑞",
    school: "四川大学",
    team: "搶曽峠杺嫿",
    type: "type1",
  },
  170: {
    members: "何林、谭淋、王超",
    school: "四川轻化工大学",
    team: "3猛男0弱鸡队",
    type: "type1",
  },
  171: {
    members: "丁誉洋、孙孜斌、殷九思",
    school: "苏州大学",
    team: "咕咕咕咕咕咕咕",
    type: "type1",
  },
  172: {
    members: "柯骅、陈夫瑞、杨哲元",
    school: "苏州大学",
    team: "哪里签到啊",
    type: "type2 unofficial",
  },
  173: {
    members: "王雨、孙楠、汤添文",
    school: "苏州大学",
    team: "喷射战士",
    type: "type2 unofficial",
  },
  174: {
    members: "周夏卿、何宇涛、陈泽豪",
    school: "苏州大学",
    team: "永不摆烂队",
    type: "type2 unofficial",
  },
  175: {
    members: "朱铭辉、杜宇轩、朱睿涵",
    school: "天津大学",
    team: "铁匠打甜酱",
    type: "type1",
  },
  176: {
    members: "王彦淞、马凯、叶泽侬",
    school: "天津大学",
    team: "五个小时怎么就这么紧呢",
    type: "type1",
  },
  177: {
    members: "郑玉柱、徐晨阳、王宇灵",
    school: "天津仁爱学院",
    team: "其实说鸽就鸽也是一种不鸽",
    type: "type1",
  },
  178: {
    members: "焦玉祥、石子悦、罗昌杰",
    school: "天津仁爱学院",
    team: "勇攀",
    type: "type1",
  },
  179: {
    members: "孙治弘、刘依扬、张乐天",
    school: "同济大学",
    team: "达拉崩吧班德贝迪卜多比鲁翁",
    type: "type1",
  },
  180: {
    members: "潘景祥、姚雨翔、屈靖恩",
    school: "同济大学",
    team: "痛苦面具",
    type: "type1",
  },
  181: {
    members: "周文杰、许世豪、孙铭迪",
    school: "台州学院",
    team: "ACM没有AC只有MAN",
    type: "type1",
  },
  182: {
    members: "冷唯诺、袁承博、王新喆",
    school: "武汉大学",
    team: "喂！摸鱼先啦！",
    type: "type1",
  },
  183: {
    members: "刘皓杰、韩文韦、王琪盛",
    school: "武汉大学",
    team: "我都可以",
    type: "type1",
  },
  184: {
    members: "杨硕、赵汝阳、张宇轩",
    school: "武汉纺织大学",
    team: "唔打代码，饮茶先啦",
    type: "type1",
  },
  185: {
    members: "范立鑫、贾金、阮云念",
    school: "武汉科技大学",
    team: "敲得要快交得要帅",
    type: "type1",
  },
  186: {
    members: "罗越、奚兆阳、徐亚萌",
    school: "武汉理工大学",
    team: "不会计数怎么办",
    type: "type1",
  },
  187: {
    members: "王孟晞、朱霖淇、潘曲阳",
    school: "西安电子科技大学",
    team: "八方旅人",
    type: "type1",
  },
  188: {
    members: "冯畅、湛忠胜、周灿",
    school: "西安电子科技大学",
    team: "辛几何旋律",
    type: "type1",
  },
  189: {
    members: "郭修屹、栾家骏、刘一可",
    school: "西安交通大学",
    team: "珈乐，嘿嘿，我的珈乐",
    type: "type1",
  },
  190: {
    members: "张晓昊、王珩、曹思宇",
    school: "西安交通大学",
    team: "舞文弄墨",
    type: "type1",
  },
  191: {
    members: "蔡祺峰、王明栋、龚城圩",
    school: "西北农林科技大学",
    team: "下次一定换个二次元队名",
    type: "type1",
  },
  192: {
    members: "文旌伍、陈越、杨龙",
    school: "西南交通大学",
    team: "CCPC奖牌零元购",
    type: "type1",
  },
  193: {
    members: "付柯翰、李一、刘阳阳",
    school: "西南科技大学",
    team: "Minya Konka",
    type: "type1",
  },
  194: {
    members: "贺禹嘉、陈胤均、李悦冰",
    school: "西南民族大学",
    team: "SMU_GZ*",
    type: "type2 unofficial",
  },
  195: {
    members: "周海龙、徐家宸、夏启弘",
    school: "西南民族大学",
    team: "SMU_GZ01",
    type: "type1",
  },
  196: {
    members: "陈家峻、易旸、谢永桦",
    school: "西南民族大学",
    team: "SMU_GZ02",
    type: "type1",
  },
  197: {
    members: "郭青硕、曲恒毅、侯天赐",
    school: "香港中文大学（深圳）",
    team: "可爱天赐摸猫猫",
    type: "type1",
  },
  198: {
    members: "忙秋阳、徐源、李冬旭",
    school: "香港中文大学（深圳）",
    team: "新手上路",
    type: "type1",
  },
  199: {
    members: "李健龙、刘世豪、赵红博",
    school: "湘潭大学",
    team: "包过",
    type: "type1",
  },
  200: {
    members: "王文海、肖志林、费高冰",
    school: "湘潭大学",
    team: "小鸡爱啄米 1.0",
    type: "type1",
  },
  201: {
    members: "李佳胜、刘彦男、罗逸聪",
    school: "新疆大学",
    team: "xju01",
    type: "type1",
  },
  202: {
    members: "吕昂、吴昌坤、陈永园",
    school: "新疆大学",
    team: "xju02",
    type: "type1",
  },
  203: {
    members: "徐心雨、田启初、孙星宇",
    school: "烟台大学",
    team: "无何有之乡",
    type: "type1",
  },
  204: {
    members: "童宗锐、丁胜、易双方",
    school: "宜春学院",
    team: "一直WA一直爽",
    type: "type1",
  },
  205: {
    members: "李嘉明、曾鹏飞、郭世力",
    school: "宜春学院",
    team: "永远Star",
    type: "type1",
  },
  206: {
    members: "王大睿、郝良友、段韬",
    school: "长春理工大学",
    team: "豌豆射手准备就绪",
    type: "type1",
  },
  207: {
    members: "周泊宇、杜雨轩、楼昌焘",
    school: "长春理工大学",
    team: "这辈子去过的地方都没有打ccpc去过的地方多，好想多打几场线下赛",
    type: "type1",
  },
  208: {
    members: "钱程、楚英杰、彭本仁",
    school: "长沙理工大学",
    team: "保底铜牌",
    type: "type1",
  },
  209: {
    members: "陈彬彬、杭帆、刘帅",
    school: "长沙理工大学",
    team: "保底优胜",
    type: "type1",
  },
  210: {
    members: "余锦鹏、孙如祥、陈申奥",
    school: "长安大学",
    team: "想为嘉然拿牌子",
    type: "type1",
  },
  211: {
    members: "王勋龙、谢涛、韩硕",
    school: "长沙学院",
    team: "Saber酱想打acm",
    type: "type1",
  },
  212: {
    members: "李炫塔、张晓鹏、庄旭东",
    school: "肇庆学院",
    team: "北岭2队",
    type: "type1",
  },
  213: {
    members: "庄博伟、苗皓淇、吕博图",
    school: "浙大城市学院",
    team: "Final Fantasy",
    type: "type1",
  },
  214: {
    members: "翁茹芸、张昊闻、沈佳力",
    school: "浙大宁波理工学院",
    team: "运气王拿外卖",
    type: "type1",
  },
  215: {
    members: "王易阳、池润拓、仇博辰",
    school: "浙江财经大学",
    team: "闪光",
    type: "type1",
  },
  216: {
    members: "赵广泽、吕耀维、凌子恒",
    school: "浙江大学",
    team: "Heltion & l1ll5 & SSerxhs",
    type: "type1",
  },
  217: {
    members: "褚朱钇恒、冯骁、陈科睿",
    school: "浙江大学",
    team: "natural anti-intelligence",
    type: "type1",
  },
  218: {
    members: "唐嘉辰、黎伟诺、李昌栋",
    school: "浙江大学",
    team: "Phantom Ensemble",
    type: "type1",
  },
  219: {
    members: "沈哲贝、胡家齐、吴迪",
    school: "浙江大学",
    team: "The cell phone battery is dead",
    type: "type1",
  },
  220: {
    members: "杨柳、冯则涛、傅嘉豪",
    school: "浙江工商大学",
    team: "锟斤拷之烫",
    type: "type1",
  },
  221: {
    members: "袁智龙、袁晨、王逸瑶",
    school: "浙江工业大学",
    team: "ZJUT6",
    type: "type1",
  },
  222: {
    members: "张宇翔、李亚伦、陈洁怡",
    school: "浙江工业大学",
    team: "地球猫猫",
    type: "type1",
  },
  223: {
    members: "胡成一、何光赋、金奇",
    school: "浙江理工大学",
    team: "才十六连wa没关系的",
    type: "type1",
  },
  224: {
    members: "葛霞霞、陈冉杨、陈允魁",
    school: "浙江农林大学",
    team: "123木头人",
    type: "type1",
  },
  225: {
    members: "王子超、陈重喜、陈城",
    school: "浙江农林大学",
    team: "春田花花幼儿园青春版",
    type: "type1",
  },
  226: {
    members: "邓鹏、陈骏鹏、方天笑",
    school: "浙江师范大学",
    team: "出发点",
    type: "type1",
  },
  227: {
    members: "王景瑶、滕佳倩、杨佳宁",
    school: "浙江师范大学",
    team: "破铜烂铁",
    type: "type2 unofficial",
  },
  228: {
    members: "王千予、谢思怡、陈心韵",
    school: "浙江师范大学",
    team: "请韩教练喝雪碧",
    type: "type2 unofficial",
  },
  229: {
    members: "丁宇洋、陈靖毅、汤浙栋",
    school: "浙江师范大学",
    team: "人生异或只如初见",
    type: "type2 unofficial",
  },
  230: {
    members: "马嘉斌、王乐琦、王威杰",
    school: "浙江师范大学",
    team: "社会主义接班银",
    type: "type2 unofficial",
  },
  231: {
    members: "叶文恺、陈骏、王学远",
    school: "浙江师范大学",
    team: "双人成行",
    type: "type2 unofficial",
  },
  232: {
    members: "温启涛、倪伟聪、厉文浩",
    school: "浙江师范大学",
    team: "星际猫",
    type: "type1",
  },
  233: {
    members: "周天辰、余知航、蒋润浩",
    school: "浙江师范大学",
    team: "妖怪被srk转走了QAQ",
    type: "type1",
  },
  234: {
    members: "陈斌格、朱梦涵、刘正永",
    school: "浙江万里学院",
    team: "苗妙妙养了只喵叫喵妙",
    type: "type1",
  },
  235: {
    members: "李浩、马少杰、邱宇",
    school: "郑州大学",
    team: "沃特提姆",
    type: "type1",
  },
  236: {
    members: "苏同、张四维、刘世纪",
    school: "郑州大学",
    team: "西海为期",
    type: "type1",
  },
  237: {
    members: "曹胜华、黄恺瑞、郎文鹏",
    school: "中国地质大学（北京）",
    team: "太奇怪了，准备交一发暴力",
    type: "type1",
  },
  238: {
    members: "张霄、王龙欢、梁孜祺",
    school: "中国计量大学",
    team: "树套树套树",
    type: "type1",
  },
  239: {
    members: "周俊峰、肖扬航、雷毅",
    school: "中国矿业大学",
    team: "塞尔达",
    type: "type1",
  },
  240: {
    members: "余湘锐、秦海、夏曦乐",
    school: "中国石油大学（北京）",
    team: "天不怕地不怕",
    type: "type1",
  },
  241: {
    members: "唐煜勋、徐国琛、李玄靖",
    school: "中南大学",
    team: "关于名字未定这件事",
    type: "type1",
  },
  242: {
    members: "郭浩博、赵伯阳、吴止境",
    school: "中南大学",
    team: "普通却自信",
    type: "type1",
  },
  243: {
    members: "何晨、叶则杨、祖淩铠",
    school: "中南大学",
    team: "行但不行",
    type: "type1",
  },
  244: {
    members: "陆尹凯、程家威、郑秋雨",
    school: "中南民族大学",
    team: "不吃香菜",
    type: "type1",
  },
  245: {
    members: "牛彦栋、叶汇亘、谢岳良",
    school: "中山大学",
    team: "中山大学_未完待续",
    type: "type1",
  },
  246: {
    members: "谢立辉、邝启鹏、邓明昱",
    school: "中山大学",
    team: "中山大学_无人之境",
    type: "type1",
  },
  247: {
    members: "欧梓洋、黄途亮、梁梓豪",
    school: "中山大学",
    team: "中山大学_最后的午餐",
    type: "type1",
  },
  248: {
    members: "李景楠、张温楷、游少濠",
    school: "中山大学",
    team: "中山大学-破空之势",
    type: "type2 unofficial",
  },
  249: {
    members: "杨天行、刘彦莹、罗以彬",
    school: "中山大学",
    team: "中山大学-天作之合",
    type: "type1",
  },
  250: {
    members: "辜飞云、崔子龙、封昊杰",
    school: "重庆邮电大学",
    team: "吃",
    type: "type1",
  },
  251: {
    members: "周笑鸥、赵越奇、李洋",
    school: "腾讯",
    team: "客村三个顶俩",
    type: "type2 unofficial",
  },
  252: {
    members: "丁其安、刘丹清、黄淼",
    school: "广州市第六中学",
    team: "卡老师阿克",
    type: "type2 unofficial",
  },
  253: {
    members: "陈悠然、郭沣、马致迅",
    school: "广州市第六中学",
    team: "魔法队",
    type: "type2 unofficial",
  },
  254: {
    members: "周逸群、李飞扬、余永哲",
    school: "中国人民解放军战略支援部队信息工程大学",
    team: "信大打铁人",
    type: "type1",
  },
};
