var teams = {
  1: {
    members: "汤锁楠、吴璇、陈星宇",
    school: "白城师范学院",
    team: "突突小分队",
    type: "type1",
  },
  2: {
    members: "杨斌、魏虹雨、王润平",
    school: "白城师范学院",
    team: "奥特曼队",
    type: "type1",
  },
  3: {
    members: "陈开桂、张家俊、谢振阳",
    school: "白城师范学院",
    team: "叙利亚男模",
    type: "type1",
  },
  4: {
    members: "蒋林峰、车林朔、赵彦君",
    school: "白城师范学院",
    team: "巧匠书院1队",
    type: "type1",
  },
  5: {
    members: "包括、陈照涵、崔英泽",
    school: "白城师范学院",
    team: "巧匠书院2队",
    type: "type1",
  },
  6: {
    members: "刘柏、刘渤超、刘文文",
    school: "白城师范学院",
    team: "AC狂魔",
    type: "type1",
  },
  7: {
    members: "吴嘉帅、张家宁、姚晗荟",
    school: "北华大学",
    team: "纯牛奶",
    type: "type1",
  },
  8: {
    members: "涂伟鸿、陈冠华、刘晓易",
    school: "北华大学",
    team: "凛冬",
    type: "type1",
  },
  9: {
    members: "王颖、李宁、王旭",
    school: "北华大学",
    team: "吃瓜三人组",
    type: "type1",
  },
  10: {
    members: "袁一骏、杜琪、杨佳乐",
    school: "北华大学",
    team: "亿元一个的茶叶蛋",
    type: "type1",
  },
  11: {
    members: "陈君杰、李军航、王振",
    school: "北华大学",
    team: "输出很大 你忍一下",
    type: "type1",
  },
  12: {
    members: "徐邦轲、周心宇、雷欣宇",
    school: "北华大学",
    team: "花",
    type: "type1",
  },
  13: {
    members: "苏荣彬、田子祺、董春杰",
    school: "北华大学",
    team: "葫芦铁头",
    type: "type1",
  },
  14: {
    members: "赵国威、刘博、范如杨",
    school: "长春大学",
    team: "要Au而不得",
    type: "type1",
  },
  15: {
    members: "项毅展、李子恒、金鑫浩",
    school: "长春大学",
    team: "蛙蛙今天wa几题",
    type: "type1",
  },
  16: {
    members: "黄雪朋、段一堂、费东旭",
    school: "长春大学",
    team: "白给队",
    type: "type1",
  },
  17: {
    members: "黄勤浩、朱子昊、贲蓬",
    school: "长春大学",
    team: "关注嘉然今天吃什么",
    type: "type1",
  },
  18: {
    members: "刘万斌、江蕲恒、姜宇恒",
    school: "长春工程学院",
    team: "代码筑城",
    type: "type1",
  },
  19: {
    members: "杨泽、刘斯诺、高宇",
    school: "长春工程学院",
    team: "蛇獴战队",
    type: "type2",
  },
  20: {
    members: "何少文、陈亚飞、赫金贺",
    school: "长春工程学院",
    team: "汪汪队蹲大牢",
    type: "type1",
  },
  21: {
    members: "薛松、简浪、李帅",
    school: "长春工程学院",
    team: "全都AC",
    type: "type1",
  },
  22: {
    members: "徐远晖、黄辰潞、高辉",
    school: "长春工程学院",
    team: "梦之队",
    type: "type1",
  },
  23: {
    members: "吴仁杰、王麒景、刘智",
    school: "长春工业大学",
    team: "饱食而遨游",
    type: "type1",
  },
  24: {
    members: "李金肖、郭畅、余欢欢",
    school: "长春工业大学",
    team: "欢畅今宵",
    type: "type1",
  },
  25: {
    members: "李昊霖、张佳琦、杨哲",
    school: "长春工业大学",
    team: "Code Always AC",
    type: "type1",
  },
  26: {
    members: "于政文、黄志鹏、韩清丞",
    school: "长春工业大学",
    team: "工大拆迁办",
    type: "type1",
  },
  27: {
    members: "樊佳腾、郭芷桐、董佳怡",
    school: "长春工业大学",
    team: "2e9+7",
    type: "type1",
  },
  28: {
    members: "季宏轩、黄金宇、陈阳平",
    school: "长春工业大学",
    team: "临江仙",
    type: "type1",
  },
  29: {
    members: "何勇杰、聂显懿、王雪涵",
    school: "长春工业大学",
    team: "sketch plane",
    type: "type1",
  },
  30: {
    members: "殷嘉楠、李腾跃、徐梦皓",
    school: "长春工业大学",
    team: "三个冒险家",
    type: "type3 unofficial",
  },
  31: {
    members: "吴镇宇、沈明轩、乔志",
    school: "长春工业大学",
    team: "背着队友偷偷WA签到题",
    type: "type3 unofficial",
  },
  32: {
    members: "贾智雯、秦嘉怡、王梓馨",
    school: "长春工业大学",
    team: "代表月亮消灭你",
    type: "type3 unofficial",
  },
  33: {
    members: "邱宏阳、章子扬、袁学成",
    school: "长春工业大学",
    team: "带带大师兄",
    type: "type3 unofficial",
  },
  34: {
    members: "张峻豪、王秋雨、蒋卓见",
    school: "长春工业大学",
    team: "I啊不CCPC冲冲冲冲冲",
    type: "type3 unofficial",
  },
  35: {
    members: "欧玉琛、李庆双、冯昌毅",
    school: "长春工业大学",
    team: "ccutsoft1",
    type: "type2",
  },
  36: {
    members: "孙荣超、李姝、李甫",
    school: "长春工业大学",
    team: "ccutsoft2",
    type: "type2",
  },
  37: {
    members: "孟启兵、杨箫淼、鲍菊香",
    school: "长春工业大学",
    team: "ccutsoft3",
    type: "type2",
  },
  38: {
    members: "曹孟凯、李文帅、姜育泽",
    school: "长春工业大学",
    team: "Hitstar1",
    type: "type3 unofficial",
  },
  39: {
    members: "秦一骏、夏友杰、刘传明",
    school: "长春工业大学",
    team: "hitStar2",
    type: "type3 unofficial",
  },
  40: {
    members: "王和威、葛海宏、马永刚",
    school: "长春工业大学",
    team: "hitstar3",
    type: "type3 unofficial",
  },
  41: {
    members: "于宏涛、徐正启、全文吉",
    school: "长春工业大学",
    team: "不工作就没有饭吃",
    type: "type1",
  },
  42: {
    members: "邢昊然、于家晨、杨壮",
    school: "长春工业大学",
    team: "20：01",
    type: "type1",
  },
  43: {
    members: "姜洪正、胡智贤、傅玲",
    school: "长春工业大学",
    team: "20：02",
    type: "type1",
  },
  44: {
    members: "何思敏、刘炳呈、孙玮",
    school: "长春工业大学",
    team: "最后的防线",
    type: "type1",
  },
  45: {
    members: "金子博、罗钟毓、桂俊强",
    school: "长春工业大学",
    team: "签到题怎么做鸭",
    type: "type1",
  },
  46: {
    members: "张航源、陶征宇、黄山",
    school: "长春工业大学人文信息学院",
    team: "达拉崩吧斑得贝迪卜多比鲁翁",
    type: "type2",
  },
  47: {
    members: "郭远、沙金枫、王徽",
    school: "长春工业大学人文信息学院",
    team: "天选福星",
    type: "type2",
  },
  48: {
    members: "田世纪、杨忠杨、包晓玉",
    school: "长春工业大学人文信息学院",
    team: "什么都做不对');drop table teams;--",
    type: "type2",
  },
  49: {
    members: "陈荣熙、冯雪、郑东辉",
    school: "长春工业大学人文信息学院",
    team: "白给小分队",
    type: "type2",
  },
  50: {
    members: "李炫坤、郑腾飞、唐贺涛",
    school: "长春工业大学人文信息学院",
    team: "昆图库塔卡提考特苏瓦西拉松",
    type: "type2",
  },
  51: {
    members: "李浩然、吴振华、侯可欣",
    school: "长春工业大学人文信息学院",
    team: "蒙达鲁克硫斯古比奇巴勒城",
    type: "type2",
  },
  52: {
    members: "叶俊毫、周煜彬、杨汉乔",
    school: "长春工业大学人文信息学院",
    team: "四零四",
    type: "type2",
  },
  53: {
    members: "宁文涛、尹娩娜、蓝凯燕",
    school: "长春光华学院",
    team: "光华1队",
    type: "type2",
  },
  54: {
    members: "米腾、李兴宇、赵晨旭",
    school: "长春光华学院",
    team: "光华2队",
    type: "type2",
  },
  55: {
    members: "叶汉、邓丹辉、罗国志",
    school: "长春光华学院",
    team: "光华3队",
    type: "type2",
  },
  56: {
    members: "贾智翔、顾辰威、谢锦思",
    school: "长春光华学院",
    team: "光华4队",
    type: "type2",
  },
  57: {
    members: "王熙睿、冯春雨、赵宇轩",
    school: "长春光华学院",
    team: "光华5队",
    type: "type2",
  },
  58: {
    members: "金晨禹、宋禹蒙、李超",
    school: "长春光华学院",
    team: "光华6队",
    type: "type2",
  },
  59: {
    members: "许豪杰、潘伟平、管志国",
    school: "长春建筑学院",
    team: "卧龙",
    type: "type2",
  },
  60: {
    members: "王哲、高聪、陈鑫海",
    school: "长春建筑学院",
    team: "从零开始的acmer生活",
    type: "type2",
  },
  61: {
    members: "王炜羿、张旻、王培安",
    school: "长春建筑学院",
    team: "凤雏",
    type: "type2",
  },
  62: {
    members: "梁天赐、鲍其跃、余英杰",
    school: "长春建筑学院",
    team: "没有队名",
    type: "type2",
  },
  63: {
    members: "李炜、徐苏超、李天宇",
    school: "长春科技学院",
    team: "三个臭皮匠",
    type: "type2",
  },
  64: {
    members: "孙鸿鹏、牟泉禹、李泽远",
    school: "长春科技学院",
    team: "我是菜鸡我怕谁",
    type: "type2",
  },
  65: {
    members: "张迎、罗鹏、程雅倩",
    school: "长春科技学院",
    team: "三个wa佬",
    type: "type2",
  },
  66: {
    members: "沈吉行、刘付萍、丁雨时",
    school: "长春理工大学",
    team: "AyouOK",
    type: "type1",
  },
  67: {
    members: "楼昌焘、李龙、石苗卉",
    school: "长春理工大学",
    team: "只有一种真正的纯白",
    type: "type1",
  },
  68: {
    members: "周泊宇、杜雨轩、毕翔伟",
    school: "长春理工大学",
    team: "冬日之阳",
    type: "type1",
  },
  69: {
    members: "王大睿、郝良友、段韬",
    school: "长春理工大学",
    team: "叁點壹肆壹伍玖贰陆伍叁伍捌玖柒玖叁贰叁捌",
    type: "type1",
  },
  70: {
    members: "于越、黄宏进、任鑫",
    school: "长春理工大学",
    team: "重金求工大厨师来长理四食堂拯救水深火热的南区学子",
    type: "type1",
  },
  71: {
    members: "铁博文、魏龙飞、周璨",
    school: "长春理工大学",
    team: "背 心 小 子",
    type: "type1",
  },
  72: {
    members: "张喆坤、俞凯元、肖泽霖",
    school: "长春理工大学",
    team: "禁止禁止套娃",
    type: "type1",
  },
  73: {
    members: "竺驰峰、刘桐、刘万超",
    school: "长春理工大学",
    team: "上阳台帖",
    type: "type1",
  },
  74: {
    members: "刘梓童、李明亮、庾艺馨",
    school: "长春理工大学",
    team: "跃龙门",
    type: "type1",
  },
  75: {
    members: "姚祥辉、董政、何铭洋",
    school: "长春理工大学",
    team: "咸鱼观光团",
    type: "type1",
  },
  76: {
    members: "吴戬、张丁根、任德智",
    school: "长春师范大学",
    team: "Nerver Settle(永不停留）",
    type: "type1",
  },
  77: {
    members: "刘泽华、郭芯瑜、周健",
    school: "长春师范大学",
    team: "TRONexe(松果计算）",
    type: "type1",
  },
  78: {
    members: "徐浩东、李翔宇、关凯铭",
    school: "东北电力大学",
    team: "HAL 9000",
    type: "type1",
  },
  79: {
    members: "赵映杰、董诗语、刘钧延",
    school: "东北电力大学",
    team: "买不到学校蜜雪冰城队",
    type: "type1",
  },
  80: {
    members: "李贵祥、冯楚婷、周锐烽",
    school: "东北电力大学",
    team: "每天睡觉八小时，昏迷十六个小时",
    type: "type1",
  },
  81: {
    members: "车宇航、汪永超、张宝宁",
    school: "东北电力大学",
    team: "不会起名",
    type: "type1",
  },
  82: {
    members: "孙芃岳、陈黄洋、钟佳明",
    school: "东北电力大学",
    team: "C0de流会梦到电子WA吗？",
    type: "type1",
  },
  83: {
    members: "王子珩、刘滨赫、徐昕阳",
    school: "东北电力大学",
    team: "求求你不要再wa了",
    type: "type1",
  },
  84: {
    members: "王博、陈正路、刘宏哲",
    school: "东北电力大学",
    team: "二食堂的买鱼强，时不时泼一碗辣酱",
    type: "type1",
  },
  85: {
    members: "牟东龙、吴宗航、陈李宏",
    school: "东北电力大学",
    team: "AC了但没完全AC",
    type: "type1",
  },
  86: {
    members: "高赫然、陈胤儒、段木多",
    school: "东北师范大学",
    team: "彼岸归航",
    type: "type1",
  },
  87: {
    members: "杨熊鑫、刘彤、凌典",
    school: "东北师范大学",
    team: "利刃的诗",
    type: "type1",
  },
  88: {
    members: "胡潇、范耀天、曾令树",
    school: "东北师范大学",
    team: "极光",
    type: "type1",
  },
  89: {
    members: "姜子健、张影、叶依航",
    school: "东北师范大学",
    team: "三个铁沸物",
    type: "type1",
  },
  90: {
    members: "李然、郝帅、朱衍哲",
    school: "东北师范大学",
    team: "哲李好帅",
    type: "type1",
  },
  91: {
    members: "童浩龙、徐文浩、唐佳成",
    school: "东北师范大学",
    team: "长夜漫漫",
    type: "type1",
  },
  92: {
    members: "史曼玲、李嘉琦、刘一木",
    school: "东北师范大学",
    team: "竹取飞翔",
    type: "type1",
  },
  93: {
    members: "张沛毅、吴越洋、宋怀智",
    school: "东北师范大学",
    team: "光子",
    type: "type1",
  },
  94: {
    members: "邹宇明、刘思博、胡哲瑜",
    school: "东北师范大学",
    team: "荧惑守心",
    type: "type1",
  },
  95: {
    members: "李赫翀、周惠龙、权祎斌",
    school: "吉林财经大学",
    team: "告白气球",
    type: "type1",
  },
  96: {
    members: "朱海阔、王伟业、李若雯",
    school: "吉林财经大学",
    team: "想AC主要看气质",
    type: "type1",
  },
  97: {
    members: "李忠祥、熊丝雨、邢思齐",
    school: "吉林财经大学",
    team: "不知道叫啥名",
    type: "type1",
  },
  98: {
    members: "崔闻悦、张轶喆、王亨朔",
    school: "吉林财经大学",
    team: "茵吹斯汀",
    type: "type1",
  },
  99: {
    members: "尹艳辉、崔瀚予、田少坤",
    school: "吉林财经大学",
    team: "代码敲不队",
    type: "type1",
  },
  100: {
    members: "谭乐家、高垚淼、刘庆鹏",
    school: "吉林财经大学",
    team: "星光闪闪",
    type: "type1",
  },
  101: {
    members: "李嘉鹏、谷余良、董帅",
    school: "吉林财经大学",
    team: "三只松鼠",
    type: "type1",
  },
  102: {
    members: "曹思祺、杨婧、徐洪伟",
    school: "吉林财经大学",
    team: "三个诸葛亮",
    type: "type1",
  },
  103: {
    members: "过思齐、陈泽祺、王品欢",
    school: "吉林大学",
    team: "世末鸽者",
    type: "type1",
  },
  104: {
    members: "方涵斌、李桢浩、徐小权",
    school: "吉林大学",
    team: "nan上加nan",
    type: "type1",
  },
  105: {
    members: "陈铭豪、黄昌盛、李光赫",
    school: "吉林大学",
    team: "嘉然小姐家的鼠鼠",
    type: "type1",
  },
  106: {
    members: "周宇恒、高钧、陈瀚",
    school: "吉林大学",
    team: "要fast不要fst",
    type: "type1",
  },
  107: {
    members: "郑翔曦、郭冠男、王鹏一",
    school: "吉林大学",
    team: "黑化肥挥发发灰会花飞",
    type: "type1",
  },
  108: {
    members: "张浩天、史镇宁、侯德亮",
    school: "吉林大学",
    team: "口头AC机",
    type: "type1",
  },
  109: {
    members: "薛坷佳、杨骥遥、程子恒",
    school: "吉林大学",
    team: "执子之手抓饼，与子偕老干妈",
    type: "type1",
  },
  110: {
    members: "夏纪源、禚景明、孙铭睿",
    school: "吉林大学",
    team: "蜡笔萌新",
    type: "type1",
  },
  111: {
    members: "郑佳策、蒋致欧、黄哲霖",
    school: "吉林大学",
    team: "乐狗",
    type: "type1",
  },
  112: {
    members: "李泽龙、薛思源、危昊韬",
    school: "吉林工业职业技术学院",
    team: "蛟龙战队",
    type: "type2",
  },
  113: {
    members: "李龙跃、谢佳宏、陈佳锋",
    school: "吉林化工学院",
    team: "喵喵队摸大鱼",
    type: "type1",
  },
  114: {
    members: "孙国庆、万瑶瑶、刘鑫淼",
    school: "吉林化工学院",
    team: "旺旺队有肉吃",
    type: "type1",
  },
  115: {
    members: "李阳、吴文豹、苏炳昆",
    school: "吉林化工学院",
    team: "颐养爆鲲",
    type: "type1",
  },
  116: {
    members: "刘宇轩、王雨、张卫东",
    school: "吉林化工学院",
    team: "天道酬勤",
    type: "type1",
  },
  117: {
    members: "姜博文、吴方伟、赵宗保",
    school: "吉林建筑大学",
    team: "翻译我不会，代码全都对",
    type: "type1",
  },
  118: {
    members: "王隐然、朱耀东、周淑姮",
    school: "吉林建筑大学",
    team: "一言为定",
    type: "type1",
  },
  119: {
    members: "战奕昕、邢成浩、欧阳强",
    school: "吉林建筑大学",
    team: "无极之道",
    type: "type1",
  },
  120: {
    members: "孙赫、司长胜、陈宪赫",
    school: "吉林建筑大学",
    team: "代码钢琴家",
    type: "type1",
  },
  121: {
    members: "张福旭、徐龙润、张思源",
    school: "吉林建筑大学",
    team: "都鸽们",
    type: "type1",
  },
  122: {
    members: "姚培茹、冯育杰、赵梦亚",
    school: "吉林建筑大学",
    team: "win号？",
    type: "type1",
  },
  123: {
    members: "洪晨展、杜存、李晔星",
    school: "吉林建筑大学",
    team: "溜不溜",
    type: "type1",
  },
  124: {
    members: "魏圣秩、朱曹灿、朱航",
    school: "吉林农业大学",
    team: "魏朱小分队",
    type: "type1",
  },
  125: {
    members: "吕星泽、邹益强、刘地华",
    school: "吉林农业大学",
    team: "我爱喝兽奶",
    type: "type1",
  },
  126: {
    members: "陈贺、郭亚丽、孙宏耀",
    school: "吉林农业科技学院",
    team: "嘉然今天吃代码",
    type: "type1",
  },
  127: {
    members: "刘耀扬、王鑫、张松",
    school: "吉林农业科技学院",
    team: "吉农科3队",
    type: "type1",
  },
  128: {
    members: "王宏凯、范俊磊、钱叶重",
    school: "吉林农业科技学院",
    team: "禁止递归爆栈",
    type: "type1",
  },
  129: {
    members: "赵鑫、张佳宁、闫旭",
    school: "吉林农业科技学院",
    team: "柠檬队",
    type: "type1",
  },
  130: {
    members: "郭洋、贾文浩、郑慧敏",
    school: "吉林农业科技学院",
    team: "我不是pwn神",
    type: "type1",
  },
  131: {
    members: "邸纪涛、刘嵩阳、郭峰",
    school: "吉林农业科技学院",
    team: "快乐地球",
    type: "type1",
  },
  132: {
    members: "林奕洋、朱文琼、马智健",
    school: "吉林农业科技学院",
    team: "快乐月球",
    type: "type1",
  },
  133: {
    members: "衣军阳、刘宗胜、闻晨晨",
    school: "吉林师范大学",
    team: "阳晨胜",
    type: "type1",
  },
  134: {
    members: "杨雁升、邓翩、李俊豪",
    school: "吉林师范大学",
    team: "绛云端",
    type: "type1",
  },
  135: {
    members: "曾远帆、吴嘉伊、王冠捷",
    school: "吉林师范大学",
    team: "比奇堡",
    type: "type1",
  },
  136: {
    members: "刘聪慧、董力赫、王小灿",
    school: "吉林师范大学",
    team: "三个看不懂题的菜鸡",
    type: "type1",
  },
  137: {
    members: "连运龙、丁瑞龙、于天浩",
    school: "吉林师范大学",
    team: "今天做的都对",
    type: "type1",
  },
  138: {
    members: "王灵祥、王泓奕、睢锦钰",
    school: "吉林师范大学博达学院",
    team: "想吃糖醋里脊糯米糕",
    type: "type2",
  },
  139: {
    members: "聂冬生、唐璇、赵弘岳",
    school: "吉林师范大学博达学院",
    team: "对对队",
    type: "type2",
  },
  140: {
    members: "童旭辉、刘新丽、毛润欣",
    school: "吉林师范大学博达学院",
    team: "晋级队",
    type: "type2",
  },
  141: {
    members: "汤顺志、李彦、张晓佳",
    school: "吉林师范大学博达学院",
    team: "头脑风暴",
    type: "type2",
  },
  142: {
    members: "刘家有、陈燕青、木景澳",
    school: "吉林师范大学博达学院",
    team: "叁三AC队",
    type: "type2",
  },
  143: {
    members: "詹鸿培、来学勇、尹贵强",
    school: "吉林师范大学博达学院",
    team: "六点八七",
    type: "type2",
  },
  144: {
    members: "陶奕成、桑龙、林甜甜",
    school: "吉林师范大学博达学院",
    team: "一拳超人",
    type: "type2",
  },
  145: {
    members: "刘顺、张继远、季欣然",
    school: "通化师范学院",
    team: "浪",
    type: "type1",
  },
  146: {
    members: "董笑言、赵战宇、刘星辰",
    school: "通化师范学院",
    team: "勇敢牛牛",
    type: "type1",
  },
  147: {
    members: "刘婉仪、周雨璇、张慧宇",
    school: "通化师范学院",
    team: "代码敲得好",
    type: "type1",
  },
  148: {
    members: "张德飞、韩家阳、徐力凯",
    school: "通化师范学院",
    team: "我们有学长带",
    type: "type1",
  },
  149: {
    members: "韩卓妍、陈麒戎、陈可",
    school: "延边大学",
    team: "延大1队",
    type: "type1",
  },
  150: {
    members: "王海涛、张博伦、周小芬",
    school: "延边大学",
    team: "延大2队",
    type: "type1",
  },
  151: {
    members: "李佳泽、杜欣慧、张子轩",
    school: "延边大学",
    team: "延大3队",
    type: "type1",
  },
  152: {
    members: "张红睿、洪川、胡月瑶",
    school: "延边大学",
    team: "延大4队",
    type: "type1",
  },
  153: {
    members: "张知玥、李泽辰、董雨龙",
    school: "延边大学",
    team: "延大5队",
    type: "type1",
  },
  154: {
    members: "张良专、郭志鹏、夏泽",
    school: "长春电子科技学院",
    team: "新世纪编程战士",
    type: "type2",
  },
  155: {
    members: "张建国、丁豪、蔡苏杭",
    school: "长春电子科技学院",
    team: "建设祖国队",
    type: "type2",
  },
  156: {
    members: "张状状、杨曙光、马骐骥",
    school: "长春电子科技学院",
    team: "灵步",
    type: "type2",
  },
  157: {
    members: "荆文博、梁家伟、林森",
    school: "长春电子科技学院",
    team: "奥里给",
    type: "type2",
  },
  158: {
    members: "张修远、于海鹏、杜春虎",
    school: "长春电子科技学院",
    team: "长电二队",
    type: "type2",
  },
  159: {
    members: "朱玉明、程泓博、杨文波",
    school: "长春电子科技学院",
    team: "烛光",
    type: "type2",
  },
  160: {
    members: "林于凯、焦惠扬、叶紫婧",
    school: "长春电子科技学院",
    team: "古灵精怪小鱼人",
    type: "type2",
  },
  161: {
    members: "夏吉、陈飞、惠常哲",
    school: "吉林工程技术师范学院",
    team: "超越自我",
    type: "type1",
  },
  162: {
    members: "粟玉辉、李虹霖、杨旭博",
    school: "吉林工程技术师范学院",
    team: "道骨仙风",
    type: "type1",
  },
  163: {
    members: "王宇辰、张君茹、蒋乐誌",
    school: "吉林工程技术师范学院",
    team: "新生上路",
    type: "type1",
  },
  164: {
    members: "崔著鹏、王华聪、郭泽娇",
    school: "吉林工程技术师范学院",
    team: "死灰复燃",
    type: "type1",
  },
  165: {
    members: "陈鑫、张文峰、吴江",
    school: "吉林建筑科技学院",
    team: "建科一队",
    type: "type2",
  },
  166: {
    members: "陈清波、汤雨鑫、姚凯源",
    school: "吉林建筑科技学院",
    team: "建科二队",
    type: "type2",
  },
  167: {
    members: "王一名、张万焜、宋坤",
    school: "吉林建筑科技学院",
    team: "建科三队",
    type: "type2",
  },
  168: {
    members: "赵文清、吕喆、杨梓文",
    school: "吉林建筑科技学院",
    team: "建科四队",
    type: "type2",
  },
  169: {
    members: "庞琳、严许霖、张颢川",
    school: "吉林建筑科技学院",
    team: "建科五队",
    type: "type2",
  },
};
