var teams = {
  333: {
    members: "韩宇、谢文鹏、胡慧",
    school: "阿坝师范学院",
    team: "卷心菜",
    type: "type1",
  },
  334: {
    members: "王泽州、王颖、金皓宇",
    school: "北京大学",
    team: "超长宕机",
    type: "type1",
  },
  336: {
    members: "牟钰、廖纪童、冯玮琪",
    school: "北京航空航天大学",
    team: "我不知道.png",
    type: "type1",
  },
  335: {
    members: "蒋贤蒙、王赵安、王智彪",
    school: "北京航空航天大学",
    team: "合法字符串",
    type: "type1",
  },
  337: {
    members: "张世东、庄禹、叶可",
    school: "北京化工大学",
    team: "随便吧，我也没想法",
    type: "type1",
  },
  338: {
    members: "赵开、刘彦铭、夏旭辉",
    school: "北京科技大学",
    team: "不可靠题意传输协议",
    type: "type1",
  },
  340: {
    members: "李坚辉、廖嘉琦、张程",
    school: "北京理工大学",
    team: "为什么你们这么熟练啊",
    type: "type1",
  },
  339: {
    members: "林恺、邹知秋、朱子林",
    school: "北京理工大学",
    team: "ddl战神",
    type: "type1",
  },
  341: {
    members: "张润泽、冯骏枝、胡德存",
    school: "北京理工大学珠海学院",
    team: "星火燎原",
    type: "type1",
  },
  342: {
    members: "牟圣豪、罗超市、于富鑫",
    school: "北京联合大学",
    team: "三个火枪手",
    type: "type2 unofficial",
  },
  1: {
    members: "吴德盛、李梦哲、王翊伟",
    school: "北京联合大学",
    team: "空山新雨",
    type: "type1",
  },
  2: {
    members: "陈浩翔、康旭、黄梓铭",
    school: "北京林业大学",
    team: "杂毛小鸡",
    type: "type1",
  },
  104: {
    members: "孙语泽、赵硕、谭英洁",
    school: "北京林业大学",
    team: "帅的举世瞩目",
    type: "type2 unofficial",
  },
  106: {
    members: "林靖轩、高艺炜、李明泽",
    school: "北京师范大学",
    team: "内测度",
    type: "type1",
  },
  4: {
    members: "赵子豪、徐悦萱、陈婉妍",
    school: "北京师范大学",
    team: "群鸦盛宴",
    type: "type1",
  },
  3: {
    members: "彭泊词、汤昕宇、卢炜文",
    school: "北京师范大学",
    team: "谢谢卡尔",
    type: "type2 unofficial",
  },
  105: {
    members: "徐若翔、何佳文、段欣然",
    school: "北京师范大学",
    team: "野指针",
    type: "type2 unofficial",
  },
  107: {
    members: "张涛、张瑞轩、张扬",
    school: "北京信息科技大学",
    team: "比赛时在做什么？有没有空？可以来局斗地主吗？",
    type: "type1",
  },
  108: {
    members: "池纪君、郑金亮、刘东岫",
    school: "北京邮电大学",
    team: "我与肚肚势不两立",
    type: "type1",
  },
  6: {
    members: "李晨曦、何宇峰、李冠谕",
    school: "北京邮电大学",
    team: "曙光黎明",
    type: "type2 unofficial",
  },
  5: {
    members: "祝梓毅、张晏宁、陈睿扬",
    school: "北京邮电大学",
    team: "咩呜米天下第一",
    type: "type1",
  },
  110: {
    members: "赵正阳、张志睿、王子骏",
    school: "北京邮电大学",
    team: "沙河摸鱼",
    type: "type2 unofficial",
  },
  7: {
    members: "孙明志、梁昊骞、林麒",
    school: "北京邮电大学",
    team: "零叉八C",
    type: "type1",
  },
  109: {
    members: "石映奇、黄思喆、王肇汉",
    school: "北京邮电大学",
    team: "北邮负一队",
    type: "type2 unofficial",
  },
  111: {
    members: "周杰、牛泽同、覃茂辉",
    school: "成都大学",
    team: "惊起wa声一片",
    type: "type1",
  },
  112: {
    members: "文健、文中星、康嘉伟",
    school: "成都东软学院",
    team: "没过四级",
    type: "type1",
  },
  8: {
    members: "王荣川、廖华杰、梁启贤",
    school: "成都东软学院",
    team: "不可思议",
    type: "type2 unofficial",
  },
  113: {
    members: "吴恒、张文渝、刘磊",
    school: "成都理工大学",
    team: "队友叫我取名字 但我不会",
    type: "type1",
  },
  124: {
    members: "陈敬龙、陈怡兵、向一心",
    school: "成都信息工程大学",
    team: "嗷呜",
    type: "type1",
  },
  114: {
    members: "高盛轩、李胤驰、余毅航",
    school: "大连理工大学",
    team: "梦觉流莺时一声",
    type: "type1",
  },
  10: {
    members: "余澍莘、袁振、卢品仁",
    school: "大连理工大学",
    team: "游侠X",
    type: "type2 unofficial",
  },
  116: {
    members: "张思凡、陈一帆、陈荣波",
    school: "大连理工大学",
    team: "异军突起",
    type: "type1",
  },
  9: {
    members: "邓思航、高金鹏、赵钧鹏",
    school: "大连理工大学",
    team: "鹏鹏今天吃什么",
    type: "type2 unofficial",
  },
  118: {
    members: "周津宇、胡佳金、朱铖昊",
    school: "电子科技大学",
    team: "UESTC_魔法少女",
    type: "type1",
  },
  117: {
    members: "弋竞为、喻鹏云、周湘阳",
    school: "电子科技大学",
    team: "UESTC_膜法少女",
    type: "type1",
  },
  115: {
    members: "陈俊杰、凤奕鸣、陈则行",
    school: "电子科技大学",
    team: "UESTC_对不起",
    type: "type1",
  },
  11: {
    members: "张镕麒、吴晓玉、梁晖",
    school: "电子科技大学",
    team: "我们仍未知道那天WA的原因",
    type: "type2 unofficial",
  },
  13: {
    members: "陈佳宝、吴宝、林国杰",
    school: "电子科技大学中山学院",
    team: "莲峰山四队",
    type: "type2 unofficial",
  },
  120: {
    members: "黄琮量、丁炤、周庭略",
    school: "电子科技大学中山学院",
    team: "吉祥如意",
    type: "type2 unofficial",
  },
  119: {
    members: "陈广辉、王宇冰、张轩",
    school: "电子科技大学中山学院",
    team: "队名什么的已经无所谓了",
    type: "type1",
  },
  12: {
    members: "王乙丞、王璐聃、胡棕宪",
    school: "电子科技大学中山学院",
    team: "椭圆卤蛋中学",
    type: "type1",
  },
  121: {
    members: "李泽仁、张晋恺、陈少皇",
    school: "东北大学",
    team: "galaxias",
    type: "type1",
  },
  122: {
    members: "胡鸿捷、袁茂恒、刘琛",
    school: "东北大学秦皇岛分校",
    team: "升空的奖牌，从台下看还是台上看？",
    type: "type1",
  },
  123: {
    members: "刘泽铭、吴一玄、罗潇阳",
    school: "东北大学秦皇岛分校",
    team: "GNK48-101",
    type: "type1",
  },
  125: {
    members: "杨坤、刘新儒、邵博宇",
    school: "东北农业大学",
    team: "都可以",
    type: "type1",
  },
  126: {
    members: "霍欣彤、李子豪、刘禹",
    school: "东北农业大学",
    team: "英语挂了就寄",
    type: "type1",
  },
  127: {
    members: "高赫然、段木多、陈胤儒",
    school: "东北师范大学",
    team: "彼岸归航",
    type: "type1",
  },
  14: {
    members: "李嘉琦、史曼玲、刘一木",
    school: "东北师范大学",
    team: "竹取飞翔",
    type: "type2 unofficial",
  },
  128: {
    members: "潘有升、方源、于永立",
    school: "东华大学",
    team: "西窗韵里任云舒",
    type: "type1",
  },
  15: {
    members: "方荥荣、郁宙、严涵",
    school: "东华大学",
    team: "还有谁不是二次元？",
    type: "type2 unofficial",
  },
  129: {
    members: "郑祎凡、潘景瑞、戚雨林",
    school: "东南大学",
    team: "猛犸不上ban",
    type: "type1",
  },
  130: {
    members: "郭嘉晟、卢芃、赵洪杰",
    school: "福建工程学院",
    team: "队友已经尽力了",
    type: "type1",
  },
  131: {
    members: "章军豪、林骅、陈坤坤",
    school: "福建师范大学",
    team: "傅老师今天吃什么",
    type: "type1",
  },
  16: {
    members: "詹涛、杨赫、程宇翔",
    school: "福州大学",
    team: "太熊软糖",
    type: "type1",
  },
  133: {
    members: "余镐、陈昊旸、苏锦程",
    school: "福州大学",
    team: "企鹅人大战谜语人",
    type: "type2 unofficial",
  },
  132: {
    members: "廖智炫、洪磊、邓宇凡",
    school: "福州大学",
    team: "午时已到",
    type: "type1",
  },
  134: {
    members: "聂绍珩、程鹏志、梁敬聪",
    school: "复旦大学",
    team: "冰泮北徂",
    type: "type1",
  },
  136: {
    members: "杜雨轩、吴可非、阮毅凡",
    school: "复旦大学",
    team: "上海爱丽丝幻乐团",
    type: "type1",
  },
  135: {
    members: "张佳洵、田嘉禾、袁榕含",
    school: "复旦大学",
    team: "邯郸路编译器",
    type: "type1",
  },
  19: {
    members: "李东明、李坤清、罗增沛",
    school: "广东工业大学",
    team: "啦啦啦",
    type: "type2 unofficial",
  },
  20: {
    members: "王泽荣、杨德荣、黄铭晖",
    school: "广东工业大学",
    team: "没吃饱没睡好",
    type: "type1",
  },
  21: {
    members: "吴汝钊、陈浩鹏、卓曜龙",
    school: "广东工业大学",
    team: "金缕衣",
    type: "type2 unofficial",
  },
  139: {
    members: "彭啸翔、曾楠、陈昱明",
    school: "广东工业大学",
    team: "蹲在树堆里",
    type: "type2 unofficial",
  },
  138: {
    members: "吴董超、刘皓瑜、谢俊",
    school: "广东工业大学",
    team: "猪猪冲冲冲",
    type: "type1",
  },
  137: {
    members: "马一凡、陈逸霖、张茜",
    school: "广东工业大学",
    team: "强力去污粉",
    type: "type2 unofficial",
  },
  18: {
    members: "李梓康、梁晓中、范琛明",
    school: "广东外语外贸大学",
    team: "不敲铜牌题",
    type: "type1",
  },
  140: {
    members: "王利明、武成志、何金洺",
    school: "广西大学",
    team: "罗小黑的牵挂",
    type: "type1",
  },
  142: {
    members: "孙城涛、洪越、阮慧鹏",
    school: "广西大学",
    team: "搞JB-ICPC",
    type: "type1",
  },
  141: {
    members: "金珉瑞、张可、蓝秋雨",
    school: "广西大学",
    team: "是谁住在深海的大菠萝里",
    type: "type1",
  },
  143: {
    members: "黄其锭、林伟、廖吉阳",
    school: "广西科技大学",
    team: "红鲤鱼与绿鲤鱼与驴",
    type: "type1",
  },
  22: {
    members: "李欣燃、陈昌浩、麻庭豪",
    school: "广西科技大学",
    team: "守护最好的猫猫星",
    type: "type1",
  },
  144: {
    members: "薛沈轲、何春霖、高业诚",
    school: "广西科技大学",
    team: "启迪明星",
    type: "type2 unofficial",
  },
  145: {
    members: "黄志聪、韦富才、罗武晨",
    school: "广西民族大学",
    team: "反卷三人组",
    type: "type1",
  },
  146: {
    members: "林熙、陆金鹤、陈奕舟",
    school: "广西民族大学",
    team: "Ceiling",
    type: "type1",
  },
  147: {
    members: "资颖泉、张文亮、黄永雄",
    school: "广西师范大学",
    team: "师大米粉",
    type: "type1",
  },
  148: {
    members: "彭云杰、何成琛、刘坤",
    school: "广西外国语学院",
    team: "这题可以二分吗",
    type: "type1",
  },
  28: {
    members: "元正臣、李学诚、陈冰鑫",
    school: "桂林电子科技大学",
    team: "灰化肥不会挥花",
    type: "type2 unofficial",
  },
  25: {
    members: "覃其洲、王鹏程、党有威",
    school: "桂林电子科技大学",
    team: "四暗刻单骑喵",
    type: "type2 unofficial",
  },
  26: {
    members: "宁申恺、苏一水、李立",
    school: "桂林电子科技大学",
    team: "广西小清华",
    type: "type2 unofficial",
  },
  29: {
    members: "周博睿、申诺、鲁智昊",
    school: "桂林电子科技大学",
    team: "毛绒绒和抱枕",
    type: "type2 unofficial",
  },
  27: {
    members: "刘思语、汪庭浩、黄思晨",
    school: "桂林电子科技大学",
    team: "无名之辈",
    type: "type2 unofficial",
  },
  24: {
    members: "陈星宇、彭鸿祥、张钰敏",
    school: "桂林电子科技大学",
    team: "一队软萌的对手",
    type: "type2 unofficial",
  },
  329: {
    members: "王阳、余秋里、徐轲",
    school: "桂林信息科技学院",
    team: "头发与你们作对",
    type: "type1",
  },
  155: {
    members: "王子恒、张睿达、梁宸菘",
    school: "国防科技大学",
    team: "万有引力号",
    type: "type1",
  },
  153: {
    members: "朱卓锋、董理、王荣航",
    school: "国防科技大学",
    team: "三个点金手",
    type: "type1",
  },
  156: {
    members: "周智、常一凡、管袁菲",
    school: "哈尔滨工程大学",
    team: "人菜瘾大",
    type: "type1",
  },
  159: {
    members: "徐文溢、魏文卿、孔佳豪",
    school: "哈尔滨工程大学",
    team: "三头老猫",
    type: "type1",
  },
  157: {
    members: "张宇驰、肖帆、魏思涵",
    school: "哈尔滨工程大学",
    team: "我来桂林吃米粉",
    type: "type1",
  },
  154: {
    members: "王洋、王昊宇、官毅",
    school: "哈尔滨工程大学",
    team: "噔噔咚",
    type: "type1",
  },
  158: {
    members: "袁野、王玺澎、陈宥羽",
    school: "哈尔滨工业大学",
    team: "奥利奥味树套树",
    type: "type1",
  },
  150: {
    members: "王子奕、付希文、唐浩云",
    school: "哈尔滨工业大学",
    team: "很有精神",
    type: "type1",
  },
  149: {
    members: "唐贝利、颜伟业、杨林翰",
    school: "哈尔滨工业大学",
    team: "奥赛罗",
    type: "type1",
  },
  160: {
    members: "蒋晨阳、杨昀昕、宋子洋",
    school: "哈尔滨工业大学（深圳）",
    team: "三阳开泰",
    type: "type1",
  },
  331: {
    members: "苏世睿、张高源、赵禹博",
    school: "哈尔滨工业大学（威海）",
    team: "WHISKYpop",
    type: "type1",
  },
  330: {
    members: "刘新一、和树繁、苑世豪",
    school: "哈尔滨工业大学（威海）",
    team: "掘金打铁",
    type: "type1",
  },
  161: {
    members: "陈嘉睿、罗江楠、张春立",
    school: "哈尔滨工业大学（威海）",
    team: "心拍数#0822",
    type: "type1",
  },
  162: {
    members: "杨志超、肖涵彬、张仪",
    school: "哈尔滨工业大学（威海）",
    team: "七仪鹿~",
    type: "type1",
  },
  163: {
    members: "邓大路、陈丁、岳金凤",
    school: "哈尔滨理工大学",
    team: "哈理工09队",
    type: "type1",
  },
  164: {
    members: "戴志炜、赵政和、尹吴潇",
    school: "杭州电子科技大学",
    team: "杭电2队",
    type: "type1",
  },
  166: {
    members: "柴汉锋、陈载元、陈思豪",
    school: "杭州电子科技大学",
    team: "杭电2021-15队",
    type: "type1",
  },
  165: {
    members: "高义雄、赵章恺、方博",
    school: "杭州电子科技大学",
    team: "杭电3队",
    type: "type1",
  },
  167: {
    members: "毛一枭、王权、来毅超",
    school: "杭州电子科技大学信息工程学院",
    team: "信工一队",
    type: "type1",
  },
  30: {
    members: "林峰、徐光泽、陈泓昕",
    school: "杭州师范大学",
    team: "仲夏夜之wa梦",
    type: "type1",
  },
  168: {
    members: "钟恺、俞佳权、徐豪杰",
    school: "杭州师范大学",
    team: "塔塔开",
    type: "type2 unofficial",
  },
  151: {
    members: "黄超龙、黄超龙张韬、阳勇权",
    school: "合肥工业大学",
    team: "来都来了",
    type: "type1",
  },
  152: {
    members: "唐志远、符尘浩、沈钰鹏",
    school: "合肥工业大学宣城校区",
    team: "跳高高",
    type: "type1",
  },
  169: {
    members: "马云龙、兰锐、胡辰阳",
    school: "合肥学院",
    team: "你一定要喊吗",
    type: "type1",
  },
  170: {
    members: "吕占捷、张圣哲、黄巍赟",
    school: "河北师范大学",
    team: "来桂林偷个银",
    type: "type1",
  },
  31: {
    members: "李佳颖、伊文慧、罗佳琦",
    school: "河北师范大学",
    team: "九天揽月",
    type: "type2 unofficial",
  },
  171: {
    members: "袁春成、蒋李程、莫慧婷",
    school: "河池学院",
    team: "这不AC，我不能接受",
    type: "type1",
  },
  172: {
    members: "刘邦龙、蔡俊宇、闫沛霖",
    school: "河南大学",
    team: "望星",
    type: "type1",
  },
  173: {
    members: "王磊、廖倍、青兆基",
    school: "贺州学院",
    team: "此处应该有",
    type: "type1",
  },
  174: {
    members: "张友、陈路迪、柯志超",
    school: "湖北第二师范学院",
    team: "未来可期",
    type: "type1",
  },
  344: {
    members: "宋丁沣、邵冲、李靓",
    school: "湖北第二师范学院",
    team: "Best Team",
    type: "type2 unofficial",
  },
  34: {
    members: "徐億祥、贺鑫宇、颜潇冉",
    school: "湖北工业大学",
    team: "读题五秒开始wa",
    type: "type2 unofficial",
  },
  33: {
    members: "洪锦辉、陈翔、孙嘉豪",
    school: "湖北工业大学",
    team: "百分之六十拿牌",
    type: "type2 unofficial",
  },
  175: {
    members: "陈廷益、柳俊、郭双奕",
    school: "湖北工业大学",
    team: "Random(name)",
    type: "type1",
  },
  32: {
    members: "吕芳莹、屈艺、平影",
    school: "湖北工业大学",
    team: "Wa哈哈哈",
    type: "type2 unofficial",
  },
  35: {
    members: "李睿欣、李佩伦、周鑫",
    school: "湖北工业大学",
    team: "特别激动小分队",
    type: "type2 unofficial",
  },
  176: {
    members: "陈增一、韦放、黄家旺",
    school: "湖南大学",
    team: "困难户",
    type: "type1",
  },
  177: {
    members: "刘晴瑞、张竣、林仁泽",
    school: "湖南工程学院",
    team: "放学后写代码",
    type: "type1",
  },
  178: {
    members: "秦豪远、周子盛、陈思源",
    school: "湖南科技大学",
    team: "烟花易逝",
    type: "type1",
  },
  179: {
    members: "严圣培、肖潇、张令轩",
    school: "湖南农业大学",
    team: "两蒂蒂夹面包",
    type: "type1",
  },
  180: {
    members: "贺禧、李隆德、黄沛遥",
    school: "湖南师范大学",
    team: "不想努力了",
    type: "type1",
  },
  181: {
    members: "杨新纪、曾铁龙、贺伦尊",
    school: "湖南文理学院",
    team: "常数太大被关了起来",
    type: "type1",
  },
  182: {
    members: "曾剑涛、刘浩然、韩祎",
    school: "华东理工大学",
    team: "那是气球吗",
    type: "type1",
  },
  184: {
    members: "刘天瑞、高祖阳、王磊",
    school: "华东师范大学",
    team: "饮茶先啦",
    type: "type2 unofficial",
  },
  183: {
    members: "章兆萌、安育东、王晨恺",
    school: "华东师范大学",
    team: "一小时写题，四小时自闭",
    type: "type1",
  },
  36: {
    members: "王鼎、李云帆、王子涵",
    school: "华东师范大学",
    team: "布朗尼",
    type: "type2 unofficial",
  },
  37: {
    members: "吴镇宇、杨贇、陈元庆",
    school: "华东师范大学",
    team: "签到题不破防",
    type: "type2 unofficial",
  },
  38: {
    members: "朱睿诚、毛博超、杨弘",
    school: "华东师范大学",
    team: "修来的福报就这么没了",
    type: "type1",
  },
  187: {
    members: "洪鹏培、张亮、丁琪",
    school: "华南理工大学",
    team: "CSP-J入门组",
    type: "type2 unofficial",
  },
  186: {
    members: "陈卓文、张以恒、熊腾浩",
    school: "华南理工大学",
    team: "橘猫终末旅行",
    type: "type1",
  },
  39: {
    members: "肖毅帆、朱逸凡、徐晖炫",
    school: "华南理工大学",
    team: "oOvO",
    type: "type1",
  },
  185: {
    members: "许一多、林靖沅、马家俊",
    school: "华南理工大学",
    team: "写不出了，饮茶先",
    type: "type1",
  },
  188: {
    members: "许智友、周俊尧、庄鑫耿",
    school: "华南农业大学",
    team: "热恋期的尧尧",
    type: "type1",
  },
  189: {
    members: "卓泽钦、陈浩鹏、何广生",
    school: "华南农业大学",
    team: "鸽",
    type: "type1",
  },
  192: {
    members: "彭学典、李乾诚、刘容舟",
    school: "华南师范大学",
    team: "好好学习天天向晚",
    type: "type1",
  },
  190: {
    members: "覃梓鑫、吴清源、黄一肯",
    school: "华南师范大学",
    team: "天江行者",
    type: "type1",
  },
  40: {
    members: "陆锦浩、甘一伟、郑子荣",
    school: "华南师范大学",
    team: "红羽魚与绿羽鱼与驴",
    type: "type2 unofficial",
  },
  191: {
    members: "黄子桓、胡丹睿、苏培哲",
    school: "华南师范大学",
    team: "母鸡救咩",
    type: "type1",
  },
  193: {
    members: "吴威明、黄燊、许昊林",
    school: "华中农业大学",
    team: "just this name",
    type: "type1",
  },
  194: {
    members: "谭雪莲、钟鸣、熊吉祥",
    school: "华中师范大学",
    team: "还我AC",
    type: "type1",
  },
  195: {
    members: "胡婧、刘政、刘一泓",
    school: "华中师范大学",
    team: "我被逐出队伍后过上社畜生活",
    type: "type1",
  },
  196: {
    members: "符智基、张仲轩、陈欣然",
    school: "惠州学院",
    team: "绽华之刻",
    type: "type1",
  },
  197: {
    members: "陈鹏、冯志勇、李昂锦",
    school: "吉首大学",
    team: "妈妈说名字太长会有傻子跟着念",
    type: "type2 unofficial",
  },
  41: {
    members: "贺俊智、石逸可、鲁承源",
    school: "吉首大学",
    team: "凤飞千仞",
    type: "type1",
  },
  198: {
    members: "林贝宁、蔡万杰、张弛",
    school: "集美大学",
    team: "抱歉，这没有集美",
    type: "type1",
  },
  199: {
    members: "麦骏、文荫华、温键伟",
    school: "暨南大学",
    team: "追光者",
    type: "type1",
  },
  200: {
    members: "朱文涛、朱渝、汪垒",
    school: "江南大学",
    team: "OP战队",
    type: "type1",
  },
  42: {
    members: "曾彪杰、程禹力、张国良",
    school: "江西理工大学",
    team: "樱花吹雪",
    type: "type1",
  },
  201: {
    members: "何嘉诚、何旭铖、汪一林",
    school: "江西理工大学",
    team: "A完这题就下机",
    type: "type2 unofficial",
  },
  202: {
    members: "周波廷、贺志飞、万鹏辉",
    school: "江西理工大学南昌校区",
    team: "纯良脆鲨",
    type: "type1",
  },
  204: {
    members: "颜玮琦、张天福、陈哲",
    school: "江西师范大学",
    team: "强氏快速嘉心糖变换",
    type: "type2 unofficial",
  },
  203: {
    members: "胡文豪、宋佑祺、田震雄",
    school: "江西师范大学",
    team: "我的二叉树被淹了",
    type: "type1",
  },
  43: {
    members: "陈康、邱熠、陈力",
    school: "江西师范大学",
    team: "去北京泡脚",
    type: "type1",
  },
  44: {
    members: "何开星、黄兴、罗雨晨",
    school: "江西师范大学",
    team: "演起来了",
    type: "type2 unofficial",
  },
  205: {
    members: "殷勇杰、雷震宇、洪梓炜",
    school: "辽宁大学",
    team: "宵待雨月",
    type: "type1",
  },
  211: {
    members: "高天、张稳、王恒",
    school: "临沂大学",
    team: "十三枪",
    type: "type1",
  },
  206: {
    members: "邹璟辰、曹跃群、刘畅",
    school: "南昌航空大学",
    team: "不管了直接交直接交",
    type: "type1",
  },
  208: {
    members: "刘谦、李菁、莫浩东",
    school: "南昌理工学院",
    team: "啾咪",
    type: "type1",
  },
  207: {
    members: "潘华成、徐文祥、凌成寿",
    school: "南昌理工学院",
    team: "无情铁首",
    type: "type1",
  },
  210: {
    members: "颜奕舟、陈璐瑶、李浩宇",
    school: "南方科技大学",
    team: "南方科技大学-奥维多",
    type: "type1",
  },
  209: {
    members: "周轶凡、田若载、曹哲振",
    school: "南方科技大学",
    team: "南方科技大学-托莱多",
    type: "type1",
  },
  212: {
    members: "许昕、王圣宇、孙瑶",
    school: "南华大学",
    team: "昨天刚学C++",
    type: "type1",
  },
  48: {
    members: "周相羽、朱家辰、贺卓宇",
    school: "南京大学",
    team: "南小饱",
    type: "type2 unofficial",
  },
  45: {
    members: "周子杰、陈思睿、徐沐杰",
    school: "南京大学",
    team: "徒手抓蛾子",
    type: "type1",
  },
  214: {
    members: "曹逸中、陈弘毅、邹忠奇",
    school: "南京大学",
    team: "如烟",
    type: "type2 unofficial",
  },
  213: {
    members: "王恺予、张乃仁、王锦朋",
    school: "南京大学",
    team: "还没想好叫什么",
    type: "type2 unofficial",
  },
  55: {
    members: "林荣恩、张浩宇、陈晓",
    school: "南京大学",
    team: "Thedereap",
    type: "type2 unofficial",
  },
  54: {
    members: "林朗、邓振霄、王诗尚",
    school: "南京大学",
    team: "本账号仅用作测试队",
    type: "type2 unofficial",
  },
  51: {
    members: "柴浩天、陈荣锴、贺柄毓",
    school: "南京大学",
    team: "菜根队",
    type: "type2 unofficial",
  },
  49: {
    members: "陈佳庚、单博、回溯",
    school: "南京大学",
    team: "不坠机就算胜利",
    type: "type2 unofficial",
  },
  53: {
    members: "陈昊洋、黄梓彦、王恺翔",
    school: "南京大学",
    team: "钟山风雨",
    type: "type2 unofficial",
  },
  46: {
    members: "陆青阳、杜星语、吴煜青",
    school: "南京大学",
    team: "admax",
    type: "type2 unofficial",
  },
  52: {
    members: "陈政弛、王宇峣、刘响",
    school: "南京大学",
    team: "六只手都在摸鱼",
    type: "type2 unofficial",
  },
  56: {
    members: "水兵、陈元旻、蒋潇鹏",
    school: "南京大学",
    team: "烂飞机",
    type: "type2 unofficial",
  },
  50: {
    members: "丁天行、单启程、欧丰宁",
    school: "南京大学",
    team: "虚幻黄昏",
    type: "type2 unofficial",
  },
  215: {
    members: "史丰萁、朱宇博、林海波",
    school: "南京大学",
    team: "猪猪今天吃了吗",
    type: "type1",
  },
  47: {
    members: "李博颖、熊丘桓、蔡之恒",
    school: "南京大学",
    team: "鸽屋咕",
    type: "type1",
  },
  216: {
    members: "钱品亦、岑嘉诚、李亚宁",
    school: "南京航空航天大学",
    team: "在CCPC寻求AC是否搞错了什么？",
    type: "type1",
  },
  218: {
    members: "陈一涵、代领、谢东娜",
    school: "南京理工大学",
    team: "三只小熊饼干",
    type: "type1",
  },
  217: {
    members: "陆宗泽、潘玉栋、谢石林",
    school: "南京理工大学",
    team: "草莓果冻",
    type: "type1",
  },
  219: {
    members: "马良、张兴洋、吴昊垲",
    school: "南京信息工程大学",
    team: "璃月之夜",
    type: "type1",
  },
  221: {
    members: "刘汪、周仕哲、岳鹏宇",
    school: "南京邮电大学",
    team: "圣母圣咏(Virgin's Rosario)",
    type: "type1",
  },
  220: {
    members: "何乐晗、陈以信、赵一舟",
    school: "南京邮电大学",
    team: "Cirtrus",
    type: "type1",
  },
  57: {
    members: "王柱、刘均圣、钟幸玲",
    school: "南宁师范大学",
    team: "酱油喝醋",
    type: "type2 unofficial",
  },
  222: {
    members: "蔡怡婷、江子良、陶德双",
    school: "南宁师范大学",
    team: "Three tofu brews",
    type: "type1",
  },
  223: {
    members: "陈潇森、刘启亮、徐斌磊",
    school: "南阳理工学院",
    team: "枯木逢春",
    type: "type1",
  },
  224: {
    members: "安康、康博、方宇杰",
    school: "内蒙古农业大学",
    team: "随便康康不AC",
    type: "type1",
  },
  225: {
    members: "赵文泽、陈挺扬、余嘉瑜",
    school: "宁波大学",
    team: "这不是人均算法吗",
    type: "type1",
  },
  58: {
    members: "张佳楠、金垄晟、张思瀚",
    school: "宁波大学",
    team: "逃离铁牌区",
    type: "type2 unofficial",
  },
  226: {
    members: "杨熠辰、刘鑫龙、王励翔",
    school: "齐鲁工业大学",
    team: "生死时速",
    type: "type1",
  },
  59: {
    members: "张泽纬、陈贺、祝奕骏",
    school: "青岛大学",
    team: "喧嚣的风",
    type: "type1",
  },
  228: {
    members: "毛聿麒、鞠传宇、董亚洲",
    school: "青岛大学",
    team: "三相之力",
    type: "type1",
  },
  61: {
    members: "何中天、周润龙、杨懋龙",
    school: "清华大学",
    team: "龙哥猫咖",
    type: "type1",
  },
  230: {
    members: "朱震霆、闫书弈、王修涵",
    school: "清华大学",
    team: "三个顶俩",
    type: "type1",
  },
  229: {
    members: "方汤骐、张哲宇、毛嘉怡",
    school: "清华大学",
    team: "盖世汤圆",
    type: "type2 unofficial",
  },
  60: {
    members: "杨乾澜、张一钊、赵赫扬",
    school: "清华大学",
    team: "疯狂宇宙",
    type: "type2 unofficial",
  },
  235: {
    members: "张俊杰、上官玄、周和",
    school: "厦门大学",
    team: "键键变秃",
    type: "type1",
  },
  233: {
    members: "周正、高言峰、徐铭逸",
    school: "厦门大学",
    team: "点分治分点",
    type: "type1",
  },
  234: {
    members: "卓子翔、陆淳杰、蔡宇航",
    school: "厦门大学嘉庚学院",
    team: "共用电子队",
    type: "type1",
  },
  236: {
    members: "门建彤、张丁祎、吴羲勇",
    school: "山东大学",
    team: "说好不秃",
    type: "type1",
  },
  66: {
    members: "王在烜、周何、卢子辰",
    school: "山东大学",
    team: "樱花猪开喵喵车创大白熊",
    type: "type2 unofficial",
  },
  63: {
    members: "耿浩天、褚瑞凡、张昊雨",
    school: "山东大学",
    team: "梦天使",
    type: "type1",
  },
  65: {
    members: "吴旭华、王展、王志伟",
    school: "山东理工大学",
    team: "来颗二营长的意大利炮",
    type: "type1",
  },
  237: {
    members: "陈柳莹、奚仲璞、刘诗蓓",
    school: "上海大学",
    team: "凑热闹队",
    type: "type2 unofficial",
  },
  232: {
    members: "徐晨凡、康高熙、王静颐",
    school: "上海大学",
    team: "面向bug程序设计",
    type: "type1",
  },
  64: {
    members: "金铖、吕定巍、周济宸",
    school: "上海大学",
    team: "秘银",
    type: "type2 unofficial",
  },
  238: {
    members: "王启隆、吴逸磊、丁东",
    school: "上海大学",
    team: "还是你懂的多啊",
    type: "type1",
  },
  239: {
    members: "徐一凡、蒋伊慧、彭昊晖",
    school: "上海大学",
    team: "极地",
    type: "type1",
  },
  62: {
    members: "张瑞之、蒋珂、吴震东",
    school: "上海大学",
    team: "正在AC中",
    type: "type2 unofficial",
  },
  240: {
    members: "王照梓、叶瑶琦、姜天乐",
    school: "上海交通大学",
    team: "柳",
    type: "type1",
  },
  241: {
    members: "范能、王子奕、冯跃洋",
    school: "上海交通大学",
    team: "重叠之梦",
    type: "type1",
  },
  67: {
    members: "余舒龙、杨余嘉、叶菁菁",
    school: "上海应用技术大学",
    team: "我很菜，你忍一下",
    type: "type1",
  },
  242: {
    members: "朱嘉钧、韩锦涛、王俞力",
    school: "上海应用技术大学",
    team: "白给",
    type: "type2 unofficial",
  },
  244: {
    members: "梁泽荣、林烨堃、杨熙全",
    school: "深圳大学",
    team: "SZU-Euclid",
    type: "type1",
  },
  243: {
    members: "连泽锋、丁潇杰、邓昌俊",
    school: "深圳大学",
    team: "SZU-Turing",
    type: "type1",
  },
  245: {
    members: "庄子琪、杨熙全、蔡壁",
    school: "深圳大学",
    team: "Emanatry",
    type: "type1",
  },
  246: {
    members: "吴咏蔚、周雪妍、郭尧",
    school: "四川大学",
    team: "给郭哥哥泡一池子大红袍",
    type: "type1",
  },
  68: {
    members: "丁誉洋、孙孜斌、殷九思",
    school: "苏州大学",
    team: "咕咕咕咕咕咕咕",
    type: "type2 unofficial",
  },
  247: {
    members: "于立恒、陆佳浩、王志庞",
    school: "苏州大学",
    team: "渐入'佳'境",
    type: "type1",
  },
  248: {
    members: "时微淳、孙宇航、黄泱邦",
    school: "苏州科技大学",
    team: "算法指难",
    type: "type1",
  },
  249: {
    members: "何玉斌、李昌荣、李沛霖",
    school: "太原理工大学",
    team: "鸽们仨",
    type: "type1",
  },
  250: {
    members: "杜鼎勋、何志凌、张博凯",
    school: "天津大学",
    team: "树状数组维护01背包",
    type: "type1",
  },
  251: {
    members: "许怿芃、樊兴宇、陈奕池",
    school: "天津大学",
    team: "三句话演队友十八分钟",
    type: "type1",
  },
  69: {
    members: "张恩辅、秦泽正、赵江",
    school: "天津商业大学",
    team: "来之不易",
    type: "type1",
  },
  254: {
    members: "朱泽凯、季马泽宇、汪冰海",
    school: "同济大学",
    team: "春田花花",
    type: "type2 unofficial",
  },
  255: {
    members: "田宇、储德明、钟伊凡",
    school: "同济大学",
    team: "要不你们起",
    type: "type2 unofficial",
  },
  70: {
    members: "夏文勇、彭瀚、孙弘毅",
    school: "同济大学",
    team: "五岁来打acm",
    type: "type1",
  },
  253: {
    members: "张迪、庞鹏瞩、高天宸",
    school: "同济大学",
    team: "快乐面具",
    type: "type1",
  },
  256: {
    members: "文柯力、张城菡、苏睿懿",
    school: "武汉大学",
    team: "柧檪森林",
    type: "type1",
  },
  257: {
    members: "王骏峣、杨宇轩、杨宇杰",
    school: "武汉大学",
    team: "鱼香猫猫",
    type: "type1",
  },
  258: {
    members: "朱少本、谢宇轩、马铭昊",
    school: "武汉大学",
    team: "在此，宣判！",
    type: "type1",
  },
  259: {
    members: "张杰、李佳毅、陈一凡",
    school: "武汉科技大学",
    team: "有人四级没过",
    type: "type1",
  },
  260: {
    members: "王昱豪、杨志刚、赵家荣",
    school: "武汉理工大学",
    team: "带花猫猫头",
    type: "type1",
  },
  73: {
    members: "欧心缘、王逸、王志利",
    school: "西安电子科技大学",
    team: "吾好梦中AC",
    type: "type2 unofficial",
  },
  252: {
    members: "蒋叶桢、曾祥翼、张炀杰",
    school: "西安电子科技大学",
    team: "转眼间又在下雨",
    type: "type2 unofficial",
  },
  71: {
    members: "王孟晞、朱霖淇、潘曲阳",
    school: "西安电子科技大学",
    team: "八方旅人",
    type: "type1",
  },
  72: {
    members: "丁雅可、陶禹成、万在舟",
    school: "西安电子科技大学",
    team: "Triy",
    type: "type1",
  },
  261: {
    members: "王舒琪、吴海怿、买志斌",
    school: "西安电子科技大学",
    team: "曾青得铁则化为铜",
    type: "type2 unofficial",
  },
  263: {
    members: "仲星焱、李纳川、陈子谦",
    school: "西安交通大学",
    team: "__builtin_clz",
    type: "type2 unofficial",
  },
  74: {
    members: "朱晨曦、施劲松、康颢",
    school: "西安交通大学",
    team: "非自然AC",
    type: "type1",
  },
  262: {
    members: "陈执镇、赵宋文、唐梓航",
    school: "西安交通大学",
    team: "我们还行吧？那当然",
    type: "type1",
  },
  264: {
    members: "徐浩然、赵铭骏、刘达可",
    school: "西安理工大学",
    team: "喵帕斯帕斯",
    type: "type1",
  },
  265: {
    members: "施景阳、郑罗承、邓云升",
    school: "西北大学",
    team: "奇怪的bug减少了",
    type: "type1",
  },
  266: {
    members: "刘成文、黄凯勋、张浩",
    school: "西北工业大学",
    team: "基地爆炸，问题不大",
    type: "type1",
  },
  267: {
    members: "李长乐、寻真、孟宪城",
    school: "西北农林科技大学",
    team: "没有人比我更懂队名",
    type: "type1",
  },
  268: {
    members: "杨涵今、梁金硕、刘璐",
    school: "西藏民族大学",
    team: "qinhan_two",
    type: "type1",
  },
  269: {
    members: "钟明汉、吴思颖、丁学敏",
    school: "西南财经大学",
    team: "爱我中华队",
    type: "type1",
  },
  270: {
    members: "刘静、杨文昊、李可欣",
    school: "西南财经大学",
    team: "天边透亮的星",
    type: "type1",
  },
  271: {
    members: "陈雯丽、刘锴睿、王宇奇",
    school: "西南大学",
    team: "西南大学啦啦队",
    type: "type1",
  },
  272: {
    members: "郑星宇、王浩源、丁一鹏",
    school: "西南交通大学",
    team: "站着挣钱",
    type: "type1",
  },
  273: {
    members: "吴宇宏、张宇含、敖睿",
    school: "西南科技大学",
    team: "梦入蟾宫",
    type: "type1",
  },
  274: {
    members: "高源、任萍、单佑婉弘",
    school: "西南科技大学",
    team: "CCPC再爱我一次",
    type: "type1",
  },
  75: {
    members: "周海龙、黄颖颖、韦懂生",
    school: "西南民族大学",
    team: "SMU_GL*",
    type: "type2 unofficial",
  },
  276: {
    members: "李锐、张洋、卿旺",
    school: "西南民族大学",
    team: "SMU_GL01",
    type: "type1",
  },
  275: {
    members: "李汝博、韩雅琪、易旸",
    school: "西南民族大学",
    team: "SMU_GL**",
    type: "type2 unofficial",
  },
  76: {
    members: "刘源、邓怀涛、刘家乐",
    school: "西南民族大学",
    team: "三青",
    type: "type1",
  },
  277: {
    members: "周伟、杨洁、谢建峰",
    school: "西南石油大学",
    team: "我为祖国献石油",
    type: "type1",
  },
  278: {
    members: "徐源、李冬旭、忙秋阳",
    school: "香港中文大学（深圳）",
    team: "新手上路(Novice on the Road)",
    type: "type1",
  },
  281: {
    members: "王应镪、胡梁宇、李博弘",
    school: "湘潭大学",
    team: "摸金铁三角",
    type: "type1",
  },
  280: {
    members: "张福、袁泽、唐路军",
    school: "湘潭大学",
    team: "嘉然，我真的好喜欢你啊",
    type: "type1",
  },
  279: {
    members: "孙涛、何璠、邝彬",
    school: "湘潭大学",
    team: "踏遍青山人未老，风景这边独好",
    type: "type1",
  },
  282: {
    members: "张嘉玮、孙康羽、李睿",
    school: "战略支援部队信息工程大学",
    team: "人活着就是为了樱岛麻衣",
    type: "type1",
  },
  78: {
    members: "袁铭蔚、朱子怡、王尉桦",
    school: "长安大学",
    team: "打完比赛去吃黄焖鸡",
    type: "type1",
  },
  79: {
    members: "李金肖、高新桂、郑婕",
    school: "长春工业大学",
    team: "花开富贵",
    type: "type2 unofficial",
  },
  77: {
    members: "吴仁杰、刘智、王麒景",
    school: "长春工业大学",
    team: "饱食而遨游",
    type: "type2 unofficial",
  },
  289: {
    members: "王闯、郭畅、余欢欢",
    school: "长春工业大学",
    team: "逆流而上",
    type: "type2 unofficial",
  },
  84: {
    members: "李龙、郝良友、王大睿",
    school: "长春理工大学",
    team: "B海蓝天，F生若梦",
    type: "type1",
  },
  81: {
    members: "肖泽霖、任鑫、刘万超",
    school: "长春理工大学",
    team: "起名越狠死的越惨",
    type: "type2 unofficial",
  },
  82: {
    members: "周泊宇、杜雨轩、楼昌焘",
    school: "长春理工大学",
    team: "这辈子去过的地方都没有打ccpc去过的地方多，好想多打几场线下赛",
    type: "type2 unofficial",
  },
  83: {
    members: "于越、毕翔伟、段韬",
    school: "长春理工大学",
    team: "好丽友·派",
    type: "type1",
  },
  283: {
    members: "铁博文、周璨、魏龙飞",
    school: "长春理工大学",
    team: "钙奶饼干",
    type: "type2 unofficial",
  },
  284: {
    members: "张喆坤、竺驰峰、俞凯元",
    school: "长春理工大学",
    team: "随波东流去",
    type: "type2 unofficial",
  },
  80: {
    members: "陈彬彬、刘帅、杭帆",
    school: "长沙理工大学",
    team: "保底优胜奖",
    type: "type1",
  },
  286: {
    members: "郑伟、刘康为、贺达",
    school: "长沙理工大学",
    team: "快来帮我找bug",
    type: "type1",
  },
  285: {
    members: "谢涛、王勋龙、韩硕",
    school: "长沙学院",
    team: "Saber酱想打acm",
    type: "type1",
  },
  287: {
    members: "庄博伟、苗皓淇、吕博图",
    school: "浙大城市学院",
    team: "Final Fantasy",
    type: "type1",
  },
  290: {
    members: "章立晨、邓皓文、田会文",
    school: "浙大城市学院",
    team: "让我研究一波",
    type: "type1",
  },
  291: {
    members: "胡志文、施舜泽、朱能熠",
    school: "浙大宁波理工学院",
    team: "火车王",
    type: "type1",
  },
  292: {
    members: "沈佳力、沈威、张昊闻",
    school: "浙大宁波理工学院",
    team: "强啊沈威",
    type: "type1",
  },
  293: {
    members: "吴祥龙、徐山钧、朱芳菲",
    school: "浙江财经大学",
    team: "曙光",
    type: "type1",
  },
  86: {
    members: "周人豪、刘洁英、赵露",
    school: "浙江财经大学",
    team: "渣男天团",
    type: "type1",
  },
  85: {
    members: "汤英杰、俞飞洋、何天益",
    school: "浙江工商大学",
    team: "键盘滚脸",
    type: "type1",
  },
  294: {
    members: "郭宇航、张殷杰、俞庄楠",
    school: "浙江工商大学",
    team: "摸鱼组000001",
    type: "type2 unofficial",
  },
  295: {
    members: "王铭阳、陈侠、许嘉俊",
    school: "浙江工商大学",
    team: "糖果超甜",
    type: "type1",
  },
  297: {
    members: "陈南君、张宇晗、姜霄",
    school: "浙江工商大学",
    team: "天天ac",
    type: "type2 unofficial",
  },
  296: {
    members: "莫清宇、杨俊尧、董烨",
    school: "浙江工业大学",
    team: "明日之盛",
    type: "type1",
  },
  299: {
    members: "陈尧、王雪龙、吴雨轩",
    school: "浙江工业大学",
    team: "我要读研",
    type: "type1",
  },
  87: {
    members: "袁佳菲、朱展乐、蒋贤潇",
    school: "浙江科技学院",
    team: "枸杞泡澡",
    type: "type1",
  },
  300: {
    members: "汤丰玮、金奇、胡成一",
    school: "浙江理工大学",
    team: "呐丶给你一颗糖",
    type: "type1",
  },
  99: {
    members: "章恒磊、周宇昕、郑懿",
    school: "浙江农林大学",
    team: "楼下大哥别过题了求求",
    type: "type1",
  },
  302: {
    members: "王荣峥、沈铖、杨悦",
    school: "浙江农林大学",
    team: "我要上蓝名",
    type: "type2 unofficial",
  },
  101: {
    members: "王景瑶、滕佳倩、杨佳宁",
    school: "浙江师范大学",
    team: "破铜烂铁",
    type: "type1",
  },
  98: {
    members: "邓鹏、陈骏鹏、方天笑",
    school: "浙江师范大学",
    team: "出发点",
    type: "type2 unofficial",
  },
  103: {
    members: "叶佳伟、张燮弛、",
    school: "浙江师范大学",
    team: "四百四十四点四只狮子",
    type: "type2 unofficial",
  },
  298: {
    members: "周天辰、余知航、蒋润浩",
    school: "浙江师范大学",
    team: "妖怪被srk转走了QAQ",
    type: "type1",
  },
  304: {
    members: "吴胜跃、许宏坚、黄彬成",
    school: "浙江师范大学",
    team: "正在加载队名",
    type: "type2 unofficial",
  },
  301: {
    members: "温启涛、倪伟聪、厉文浩",
    school: "浙江师范大学",
    team: "星际猫",
    type: "type2 unofficial",
  },
  100: {
    members: "郑顺帆、黄蔡晨、李宇昂",
    school: "浙江师范大学",
    team: "戏剧表演者",
    type: "type2 unofficial",
  },
  102: {
    members: "吴铮、张文枫、吴支飞",
    school: "浙江师范大学",
    team: "乐事只吃原味",
    type: "type2 unofficial",
  },
  88: {
    members: "陈斌格、朱梦涵、刘正永",
    school: "浙江万里学院",
    team: "苗妙妙养了只喵叫喵妙",
    type: "type1",
  },
  303: {
    members: "郭义杰、周启鸿、陈星伟",
    school: "浙江万里学院",
    team: "九章算术",
    type: "type1",
  },
  305: {
    members: "盛子阳、饶易安、何雁杰",
    school: "浙江中医药大学",
    team: "ZCMU-春风不度雁阳安",
    type: "type2 unofficial",
  },
  17: {
    members: "王元、朱家伟、李弘辰",
    school: "浙江中医药大学",
    team: "ZCMU-高行微言，所以修身",
    type: "type1",
  },
  308: {
    members: "张四维、刘世纪、苏同",
    school: "郑州大学",
    team: "西海为期",
    type: "type1",
  },
  307: {
    members: "吴程程、王博、姚建业",
    school: "郑州大学",
    team: "圣嘉然之力",
    type: "type1",
  },
  309: {
    members: "宋江、张永林、张纪龙",
    school: "郑州轻工业大学",
    team: "la_soleil",
    type: "type1",
  },
  90: {
    members: "刘建顺、张文涛、张佳豪",
    school: "中北大学",
    team: "今朝有牌",
    type: "type2 unofficial",
  },
  310: {
    members: "车林奇、张佳鹏、张润齐",
    school: "中北大学",
    team: "祝晴",
    type: "type1",
  },
  93: {
    members: "师文帅、梁晓赟、平妃帆",
    school: "中北大学",
    team: "流光点点",
    type: "type2 unofficial",
  },
  89: {
    members: "王少鹏、张舟、张超",
    school: "中北大学",
    team: "逆三角",
    type: "type2 unofficial",
  },
  91: {
    members: "冀武韬、柴孟陶、郭锦涛",
    school: "中北大学",
    team: "三tao之队",
    type: "type2 unofficial",
  },
  92: {
    members: "王海深、赵守智、王皓男",
    school: "中北大学",
    team: "无B树-唯AC",
    type: "type2 unofficial",
  },
  311: {
    members: "胡世琦、姚顺玙、赵笑天",
    school: "中国地质大学（北京）",
    team: "为美好的世界献上祝福",
    type: "type1",
  },
  312: {
    members: "何永鑫、付欣宇、于桐",
    school: "中国地质大学（武汉）",
    team: "背着队友偷偷wa题",
    type: "type1",
  },
  94: {
    members: "赵霄、朱天泽、战翔宇",
    school: "中国地质大学（武汉）",
    team: "香水有毒",
    type: "type1",
  },
  313: {
    members: "吕筱玮、葛足澳、张子涵",
    school: "中国海洋大学",
    team: "不听不听，飞鞋点金",
    type: "type1",
  },
  314: {
    members: "李睿杰、张成玺、刘承诚",
    school: "中国海洋大学",
    team: "树上的鸟儿成双队",
    type: "type2 unofficial",
  },
  315: {
    members: "张霄、王龙欢、梁孜祺",
    school: "中国计量大学",
    team: "树套树套树",
    type: "type1",
  },
  316: {
    members: "周正谊、林仁豪、陈浩男",
    school: "中国计量大学现代科技学院",
    team: "我的学校真的绿色",
    type: "type1",
  },
  318: {
    members: "周一凡、孙旭磊、赵泽昆",
    school: "中国科学技术大学",
    team: "about:blank",
    type: "type1",
  },
  319: {
    members: "赵奕、边锋、殷跃然",
    school: "中国科学技术大学",
    team: "中科大附属第一小学",
    type: "type1",
  },
  317: {
    members: "方驰正、周瓯翔、陈卫星",
    school: "中国科学技术大学",
    team: "Firezox",
    type: "type1",
  },
  332: {
    members: "周俊峰、雷毅、肖扬航",
    school: "中国矿业大学",
    team: "塞尔达",
    type: "type1",
  },
  321: {
    members: "卢秋阳、周扬、李浩宇",
    school: "中南大学",
    team: "队友竟被嘉然...【展开阅读】",
    type: "type1",
  },
  322: {
    members: "何晨、叶则杨、祖淩铠",
    school: "中南大学",
    team: "行但不行",
    type: "type2 unofficial",
  },
  95: {
    members: "黄道煜、张皓然、周霄羽",
    school: "中南大学",
    team: "摸鱼自动机",
    type: "type1",
  },
  320: {
    members: "郭浩博、赵伯阳、吴止境",
    school: "中南大学",
    team: "普通却自信",
    type: "type1",
  },
  323: {
    members: "陆尹凯、程家威、郑秋雨",
    school: "中南民族大学",
    team: "不吃香菜",
    type: "type2 unofficial",
  },
  96: {
    members: "连雨豪、李继鹤、王翔",
    school: "中南民族大学",
    team: "铜之力",
    type: "type1",
  },
  326: {
    members: "陈宇浩、张涛麟、谢文龙",
    school: "中山大学",
    team: "无效相应",
    type: "type1",
  },
  325: {
    members: "欧梓洋、黄途亮、梁梓豪",
    school: "中山大学",
    team: "中山大学_最后的午餐",
    type: "type1",
  },
  97: {
    members: "梁励、曾比、吴景图",
    school: "中山大学",
    team: "中山大学-卡布奇诺",
    type: "type1",
  },
  327: {
    members: "黄瀚、冯嘉乐、刘卓逸",
    school: "中山大学",
    team: "中山大学-银河的光子",
    type: "type1",
  },
  324: {
    members: "刘思然、王子睿、谢泽熙",
    school: "中山大学",
    team: "中山大学_晴栀",
    type: "type2 unofficial",
  },
  328: {
    members: "黄锐、黄思源、王冀鲁",
    school: "重庆大学",
    team: "狂封智力",
    type: "type1",
  },
};
